// =====================================================
// FOUNDEROS
// OPERATING INTELLIGENCE SETUP WIDGET
// UI orchestration for existing Commander authorities only.
// =====================================================

(function () {
  if (typeof window === "undefined" || typeof document === "undefined") return;
  const $ = (id) => document.getElementById(id);
  const ids = ["operating-setup-status", "operating-setup-error", "operating-situation-current", "operating-situation-subject", "operating-situation-reality", "operating-situation-form", "operating-situation-subject-input", "operating-situation-reality-input", "operating-situation-submit", "operating-situation-edit", "operating-situation-close", "operating-move-current", "operating-move-absent", "operating-move-prerequisite", "operating-move-action", "operating-move-form", "operating-move-action-input", "operating-move-submit", "operating-move-edit", "operating-move-withdraw", "operating-context-current", "operating-context-scoped", "operating-context-open", "operating-context-clear", "operating-policy-clarify", "operating-policy-current", "operating-policy-submit", "operating-policy-clear", "operating-policy-guidance"];
  const node = Object.fromEntries(ids.map((id) => [id, $(id)])); if (Object.values(node).some((value) => !value)) return;
  let editingSituation = false; let editingMove = false;
  const owner = (name, method) => { const value = name === "SituationSystem" ? (typeof SituationSystem === "undefined" ? null : SituationSystem) : name === "CandidateMoveSystem" ? (typeof CandidateMoveSystem === "undefined" ? null : CandidateMoveSystem) : name === "CommanderContextSystem" ? (typeof CommanderContextSystem === "undefined" ? null : CommanderContextSystem) : name === "CommanderAttentionPolicySystem" ? (typeof CommanderAttentionPolicySystem === "undefined" ? null : CommanderAttentionPolicySystem) : null; return value && typeof value[method] === "function" ? value : null; };
  const read = (name, method) => { const value = owner(name, method); if (!value) return { status: "unavailable" }; try { return value[method](); } catch (error) { return { status: "unavailable" }; } };
  const error = (message = "") => { node["operating-setup-error"].textContent = message; };
  const message = (value) => value && value.message ? value.message : value instanceof Error ? value.message : "The recorded authority could not be updated.";
  const current = () => ({ situation: read("SituationSystem", "getSituation"), move: read("CandidateMoveSystem", "getCandidateMove"), context: read("CommanderContextSystem", "getContext"), policy: read("CommanderAttentionPolicySystem", "getAttentionPolicy") });
  const available = (state) => state && state.status === "available" && state.current;
  const active = (state) => available(state) && (state.current.status === "active" || state.current.carryStatus === "active");
  function render() {
    const state = current(); const situationRecord = available(state.situation) ? state.situation.current : null; const moveRecord = available(state.move) ? state.move.current : null; const situation = active(state.situation) ? state.situation.current : null; const move = active(state.move) ? state.move.current : null; const context = active(state.context) ? state.context.current : null; const policy = active(state.policy) ? state.policy.current : null;
    const unavailable = Object.values(state).some((value) => value.status === "unavailable");
    node["operating-setup-status"].textContent = unavailable ? "Unavailable" : situation && move && context && policy ? "Core operating setup established" : context && policy && !move ? "Authority ready; no current move" : "Core operating setup incomplete";
    node["operating-situation-current"].hidden = !situationRecord; node["operating-situation-form"].hidden = !!situationRecord && !editingSituation;
    if (situationRecord) { node["operating-situation-subject"].textContent = situationRecord.subject; node["operating-situation-reality"].textContent = situationRecord.carryStatus === "closed" ? `${situationRecord.currentReality} (Recorded Situation is closed.)` : situationRecord.currentReality; if (editingSituation && situation) { node["operating-situation-reality-input"].value = situation.currentReality; node["operating-situation-submit"].textContent = "Update Current Reality"; } } else { node["operating-situation-submit"].textContent = "Record Situation"; }
    node["operating-situation-edit"].hidden = !situation; node["operating-situation-close"].hidden = !situation;
    node["operating-move-current"].hidden = !moveRecord; node["operating-move-absent"].hidden = !!moveRecord; node["operating-move-prerequisite"].hidden = !!situation || !!moveRecord; node["operating-move-form"].hidden = !!moveRecord && !editingMove || !situation;
    if (moveRecord) { node["operating-move-action"].textContent = moveRecord.status === "withdrawn" ? `${moveRecord.action} (Current Move is withdrawn.)` : moveRecord.action; if (editingMove && move) { node["operating-move-action-input"].value = move.action; node["operating-move-submit"].textContent = "Update Current Move"; } } else { node["operating-move-submit"].textContent = "Record Current Move"; }
    node["operating-move-edit"].hidden = !move; node["operating-move-withdraw"].hidden = !move;
    node["operating-move-submit"].disabled = !situation;
    node["operating-context-current"].textContent = state.context.status === "absent" ? "No operating scope is established." : state.context.status === "unavailable" ? "Operating scope is unavailable." : state.context.current.status === "cleared" ? "Operating scope was cleared." : context.scope.mode === "open" ? "Open Context is active. Use the current Context without narrowing it to this one recorded situation." : "Only this recorded situation is active. Include candidates connected to this recorded situation.";
    node["operating-context-scoped"].disabled = !situation || unavailable; node["operating-context-open"].disabled = unavailable; node["operating-context-clear"].hidden = !available(state.context);
    const clarify = policy && policy.rules.some((rule) => rule.conditions.length === 1 && rule.conditions[0] === "move.clarify"); node["operating-policy-clarify"].checked = !!clarify;
    node["operating-policy-current"].textContent = state.policy.status === "absent" ? "No Attention Policy is established." : state.policy.status === "unavailable" ? "Attention Policy is unavailable." : state.policy.current.status === "cleared" ? "Attention Policy was cleared." : clarify ? "Attention Policy is active for recorded moves that need more operating truth." : "Attention Policy is active with categories not editable in this setup surface.";
    node["operating-policy-clear"].hidden = !policy; node["operating-policy-submit"].textContent = policy ? "Replace Attention Policy" : "Establish Attention Policy";
  }
  function invoke(work) { error(); try { work(); editingSituation = false; editingMove = false; render(); } catch (failure) { error(message(failure)); render(); } }
  node["operating-situation-form"].addEventListener("submit", (event) => { event.preventDefault(); invoke(() => { const state = read("SituationSystem", "getSituation"); const api = owner("SituationSystem", editingSituation ? "correctSituation" : "createSituation"); if (!api) throw new Error("Situation authority is unavailable."); if (editingSituation) api.correctSituation({ id: state.current.id, expectedRevision: state.current.revision, currentReality: node["operating-situation-reality-input"].value }); else api.createSituation({ subject: node["operating-situation-subject-input"].value, currentReality: node["operating-situation-reality-input"].value }); }); });
  node["operating-situation-edit"].addEventListener("click", () => { editingSituation = true; render(); });
  node["operating-situation-close"].addEventListener("click", () => invoke(() => { const state = read("SituationSystem", "getSituation"); const api = owner("SituationSystem", "closeSituation"); if (!active(state) || !api) throw new Error("Situation authority is unavailable."); api.closeSituation({ id: state.current.id, expectedRevision: state.current.revision }); }));
  node["operating-move-form"].addEventListener("submit", (event) => { event.preventDefault(); invoke(() => { const situation = read("SituationSystem", "getSituation"); const move = read("CandidateMoveSystem", "getCandidateMove"); const api = owner("CandidateMoveSystem", editingMove ? "correctCandidateMove" : "createCandidateMove"); if (!active(situation) || !api) throw new Error("An active recorded Situation is required."); if (editingMove) api.correctCandidateMove({ id: move.current.id, expectedRevision: move.current.revision, action: node["operating-move-action-input"].value }); else api.createCandidateMove({ situationId: situation.current.id, action: node["operating-move-action-input"].value }); }); });
  node["operating-move-edit"].addEventListener("click", () => { editingMove = true; render(); });
  node["operating-move-withdraw"].addEventListener("click", () => invoke(() => { const state = read("CandidateMoveSystem", "getCandidateMove"); const api = owner("CandidateMoveSystem", "withdrawCandidateMove"); if (!active(state) || !api) throw new Error("Current Move authority is unavailable."); api.withdrawCandidateMove({ id: state.current.id, expectedRevision: state.current.revision }); }));
  function setContext(mode) { invoke(() => { const state = read("CommanderContextSystem", "getContext"); const situation = read("SituationSystem", "getSituation"); const expectedRevision = state.status === "absent" ? 0 : state.current.revision; const api = owner("CommanderContextSystem", mode === "open" ? "setOpenContext" : "setScopedContext"); if (!api || mode !== "open" && !active(situation)) throw new Error("Recorded Situation authority is required for this scope."); if (mode === "open") api.setOpenContext({ expectedRevision }); else api.setScopedContext({ situationIds: [situation.current.id], expectedRevision }); }); }
  node["operating-context-open"].addEventListener("click", () => setContext("open")); node["operating-context-scoped"].addEventListener("click", () => setContext("scoped"));
  node["operating-context-clear"].addEventListener("click", () => invoke(() => { const state = read("CommanderContextSystem", "getContext"); const api = owner("CommanderContextSystem", "clearContext"); if (!available(state) || !api) throw new Error("Operating scope is unavailable."); api.clearContext({ expectedRevision: state.current.revision }); }));
  node["operating-policy-submit"].addEventListener("click", () => { if (!node["operating-policy-clarify"].checked) { node["operating-policy-guidance"].textContent = "Select at least one supported awareness category to establish this initial policy."; return; } node["operating-policy-guidance"].textContent = ""; invoke(() => { const state = read("CommanderAttentionPolicySystem", "getAttentionPolicy"); const api = owner("CommanderAttentionPolicySystem", active(state) ? "replaceAttentionPolicy" : "establishAttentionPolicy"); if (!api || state.status === "unavailable") throw new Error("Attention Policy authority is unavailable."); api[active(state) ? "replaceAttentionPolicy" : "establishAttentionPolicy"]({ rules: [["move.clarify"]], expectedRevision: state.status === "absent" ? 0 : state.current.revision }); }); });
  node["operating-policy-clear"].addEventListener("click", () => invoke(() => { const state = read("CommanderAttentionPolicySystem", "getAttentionPolicy"); const api = owner("CommanderAttentionPolicySystem", "clearAttentionPolicy"); if (!available(state) || !api) throw new Error("Attention Policy authority is unavailable."); api.clearAttentionPolicy({ expectedRevision: state.current.revision }); }));
  window.OperatingSetupWidget = { render };
  if (document.readyState === "loading" && typeof window.addEventListener === "function") window.addEventListener("load", render, { once: true }); else render();
})();
