const test = require("node:test"); const assert = require("node:assert/strict"); const fs = require("node:fs"); const path = require("node:path"); const vm = require("node:vm");
const root = path.resolve(__dirname, ".."); const files = ["js/storage.js", "systems/commander.system.js", "systems/situation.system.js", "systems/candidate-move.system.js", "systems/candidate-move-hold.system.js", "systems/candidate-move-dependency.system.js", "systems/candidate-move-availability.system.js", "systems/candidate-move-commitment.system.js", "systems/candidate-move-routine.system.js", "systems/commander-context.system.js", "systems/move-state.system.js", "systems/attention-candidate.system.js"]; const source = Object.fromEntries(files.map((f) => [f, fs.readFileSync(path.join(root, f), "utf8")]));
const clone = (v) => JSON.parse(JSON.stringify(v)); const asOf = "2026-09-18T10:00:00.000Z"; const schedule = { kind: "weekly-utc", weekday: 5, opensAtUtc: "09:00:00Z", closesAtUtc: "17:00:00Z" };
// Keep lifecycle writes before the fixed evaluation dates, independent of the wall clock.
function testClock(now = "2026-09-18T08:00:00.000Z") {
  let time = Date.parse(now);
  return class extends Date {
    constructor(...args) { super(...(args.length ? args : [time])); }
    static now() { return time; }
    static setTime(value) { time = Date.parse(value); }
  };
}
function store(initial = {}, behavior = {}) { const values = new Map(Object.entries(initial)); const operations = []; return { get length() { return values.size; }, key(i) { return Array.from(values.keys())[i] || null; }, getItem(k) { operations.push(["get", k]); return values.has(k) ? values.get(k) : null; }, setItem(k, v) { operations.push(["set", k]); if (behavior.setItem) behavior.setItem(k, String(v), values); else values.set(k, String(v)); }, removeItem(k) { values.delete(k); }, values, operations }; }
function load({ now } = {}) { const clock = testClock(now); const localStorage = store(); const calls = { memory: 0, notification: 0, refresh: 0 }; const context = vm.createContext({ Date: clock, Math, JSON, localStorage, sessionStorage: store(), console: { warn() {}, error() {} }, MemorySystem: { saveArtifact() { calls.memory += 1; } }, showNotification() { calls.notification += 1; }, refreshSession() { calls.refresh += 1; } }); for (const f of files) vm.runInContext(source[f], context, { filename: f }); vm.runInContext(";globalThis.__api={founder,loadFounder,CommanderSystem,SituationSystem,CandidateMoveSystem,CandidateMoveCommitmentSystem,CandidateMoveRoutineSystem,CommanderContextSystem,MoveStateSystem,AttentionCandidateSystem};", context); return { api: context.__api, localStorage, calls, clock }; }
function setup(options = {}) { const h = load(options); h.api.loadFounder(); const s = h.api.SituationSystem.createSituation({ subject: "Package", currentReality: "Ready." }); const m = h.api.CandidateMoveSystem.createCandidateMove({ situationId: s.id, action: "Send package." }); return { h, s, m }; } function candidate(h) { return h.api.AttentionCandidateSystem.getCandidates({ asOf }); }

test("asOf is required canonical UTC, has no clock fallback, and valid absent sources give an empty list", () => { const h = load(); h.api.loadFounder(); for (const value of [undefined, "bad", "2026-09-18T10:00:00Z", "2026-09-18T10:00:00.000+00:00"]) assert.equal(h.api.AttentionCandidateSystem.getCandidates({ asOf: value }).status, "unavailable"); const before = h.localStorage.operations.length; assert.deepEqual(clone(candidate(h)), { status: "available", asOf, candidates: [] }); assert.equal(h.localStorage.operations.length, before); });

test("Move State actionable, waiting, hold, and clarify normalize one exact current revision move basis", () => { for (const [state, kind] of [["actionable", "availability"], ["waiting", "dependency"], ["hold", "hold"], ["clarify", "insufficient-operating-truth"]]) { const { h, m } = setup(); h.api.MoveStateSystem.getMoveState = () => ({ status: "available", state, candidateMoveId: m.id, candidateMoveRevision: 1, basis: { kind, references: [] } }); const output = candidate(h); assert.equal(output.candidates.length, 1); assert.deepEqual(clone(output.candidates[0].bases[0]), { kind: "move", moveState: state, stateBasis: { kind, references: [] } }); } });

test("active Commitment and current Routine occurrence group with move, preserve exact temporal facts, and receive exact asOf", () => { const { h, m } = setup(); const commitment = h.api.CandidateMoveCommitmentSystem.createCommitment({ candidateMoveId: m.id, expectedCandidateMoveRevision: 1, window: { kind: "deadline", dueAt: "2026-09-18T09:00:00.000Z" } }); const routine = h.api.CandidateMoveRoutineSystem.createRoutine({ candidateMoveId: m.id, expectedCandidateMoveRevision: 1, schedule }); let commitmentAsOf; let routineAsOf; const window = h.api.CandidateMoveCommitmentSystem.getCommitmentWindowState; const occurrence = h.api.CandidateMoveRoutineSystem.getRoutineOccurrence; h.api.CandidateMoveCommitmentSystem.getCommitmentWindowState = (input) => { commitmentAsOf = input.asOf; return window.call(h.api.CandidateMoveCommitmentSystem, input); }; h.api.CandidateMoveRoutineSystem.getRoutineOccurrence = (input) => { routineAsOf = input.asOf; return occurrence.call(h.api.CandidateMoveRoutineSystem, input); }; const result = candidate(h); assert.equal(result.status, "available"); assert.equal(commitmentAsOf, asOf); assert.equal(routineAsOf, asOf); assert.equal(result.candidates.length, 1); assert.deepEqual(result.candidates[0].bases.map((b) => b.kind), ["move", "commitment", "routine-occurrence"]); assert.equal(result.candidates[0].bases[1].commitmentId, commitment.id); assert.equal(result.candidates[0].bases[1].deadlineState, "passed"); assert.equal(result.candidates[0].bases[2].routineId, routine.id); });

test("historical active Commitment after correction remains a distinct exact-revision candidate; withdrawal keeps it while removing move", () => { const { h, m } = setup(); h.api.CandidateMoveCommitmentSystem.createCommitment({ candidateMoveId: m.id, expectedCandidateMoveRevision: 1, window: { kind: "deadline", dueAt: "2026-09-30T19:00:00.000Z" } }); h.api.CandidateMoveSystem.correctCandidateMove({ id: m.id, expectedRevision: 1, action: "Send revised package." }); let result = candidate(h); assert.deepEqual(result.candidates.map((c) => c.candidateMoveRevision), [1, 2]); assert.deepEqual(result.candidates[0].bases.map((b) => b.kind), ["commitment"]); assert.deepEqual(result.candidates[1].bases.map((b) => b.kind), ["move"]); h.api.CandidateMoveSystem.withdrawCandidateMove({ id: m.id, expectedRevision: 2 }); result = candidate(h); assert.equal(result.candidates.length, 1); assert.equal(result.candidates[0].candidateMoveRevision, 1); assert.equal(result.candidates[0].bases[0].kind, "commitment"); });

test("completed/canceled commitments and paused/retired/outside routines create no basis, while source failures fail the complete list", () => { const { h, m } = setup(); const c = h.api.CandidateMoveCommitmentSystem.createCommitment({ candidateMoveId: m.id, expectedCandidateMoveRevision: 1, window: { kind: "deadline", dueAt: "2026-09-30T19:00:00.000Z" } }); h.api.CandidateMoveCommitmentSystem.completeCommitment({ id: c.id, expectedRevision: 1 }); const r = h.api.CandidateMoveRoutineSystem.createRoutine({ candidateMoveId: m.id, expectedCandidateMoveRevision: 1, schedule }); h.api.CandidateMoveRoutineSystem.pauseRoutine({ id: r.id, expectedRevision: 1 }); assert.deepEqual(candidate(h).candidates[0].bases.map((b) => b.kind), ["move"]); h.api.CandidateMoveCommitmentSystem.getCommitments = () => ({ status: "unavailable" }); assert.equal(candidate(h).status, "unavailable"); });

test("malformed owner contracts, active unexpected not-applicable, duplicate identities, and thrown owners fail closed", () => { const { h, m } = setup(); h.api.MoveStateSystem.getMoveState = () => ({ status: "not-applicable" }); assert.equal(candidate(h).status, "unavailable"); h.api.MoveStateSystem.getMoveState = () => ({ status: "available", state: "actionable", candidateMoveId: m.id, candidateMoveRevision: 1, basis: { kind: "wrong", references: [] } }); assert.equal(candidate(h).status, "unavailable"); h.api.MoveStateSystem.getMoveState = () => { throw new Error("bad"); }; assert.equal(candidate(h).status, "unavailable"); });

test("Context is never consulted; reads are detached, deterministic, side-effect free, and contain no Attention judgment", () => { const { h, m } = setup(); h.api.CommanderContextSystem.getContext = () => { throw new Error("must not read Context"); }; const before = clone(h.api.founder); const storageWrites = h.localStorage.operations.filter(([t]) => t === "set").length; const first = candidate(h); const second = candidate(h); first.candidates[0].bases[0].stateBasis.kind = "bad"; assert.equal(second.candidates[0].bases[0].stateBasis.kind, "insufficient-operating-truth"); assert.deepEqual(clone(h.api.founder), before); assert.equal(h.localStorage.operations.filter(([t]) => t === "set").length, storageWrites); assert.deepEqual(h.calls, { memory: 0, notification: 0, refresh: 0 }); for (const c of second.candidates) for (const key of ["priority", "urgency", "attention", "score", "rank", "recommendation", "shouldAct", "interrupt"]) assert.equal(Object.hasOwn(c, key), false); assert.equal(m.id, second.candidates[0].candidateMoveId); });

test("Commitment adversarial payloads and temporal result mismatches fail the entire list", () => { const { h, m } = setup(); const created = h.api.CandidateMoveCommitmentSystem.createCommitment({ candidateMoveId: m.id, expectedCandidateMoveRevision: 1, window: { kind: "deadline", dueAt: "2026-09-30T19:00:00.000Z" } }); const get = h.api.CandidateMoveCommitmentSystem.getCommitments; const window = h.api.CandidateMoveCommitmentSystem.getCommitmentWindowState; const cases = [
  () => ({ status: "available", records: {} }),
  () => { const x = get.call(h.api.CandidateMoveCommitmentSystem); x.records.push(clone(x.records[0])); return x; },
  () => { const x = get.call(h.api.CandidateMoveCommitmentSystem); x.records[0].candidateMoveId = "candidate_move_bad_x"; return x; },
  () => { const x = get.call(h.api.CandidateMoveCommitmentSystem); x.records[0].candidateMoveRevision = 99; return x; },
  () => { const x = get.call(h.api.CandidateMoveCommitmentSystem); x.records[0].acceptedAction = "wrong"; return x; },
]; for (const make of cases) { h.api.CandidateMoveCommitmentSystem.getCommitments = make; assert.equal(candidate(h).status, "unavailable"); } h.api.CandidateMoveCommitmentSystem.getCommitments = get; for (const make of [() => ({ status: "available", id: created.id, lifecycle: "active", dueAt: "bad", windowState: "open", evaluatedAt: asOf }), () => ({ status: "available", id: "wrong", lifecycle: "active", dueAt: "2026-09-30T19:00:00.000Z", windowState: "open", evaluatedAt: asOf }), () => ({ status: "available", id: created.id, lifecycle: "active", dueAt: "2026-09-30T19:00:00.000Z", windowState: "open", evaluatedAt: "2026-09-18T10:00:01.000Z" })]) { h.api.CandidateMoveCommitmentSystem.getCommitmentWindowState = make; assert.equal(candidate(h).status, "unavailable"); } h.api.CandidateMoveCommitmentSystem.getCommitmentWindowState = window; });

test("Routine adversarial collection and occurrence payloads fail closed without mutating owner arrays", () => { const { h, m } = setup(); const routine = h.api.CandidateMoveRoutineSystem.createRoutine({ candidateMoveId: m.id, expectedCandidateMoveRevision: 1, schedule }); const get = h.api.CandidateMoveRoutineSystem.getRoutines; const occurrence = h.api.CandidateMoveRoutineSystem.getRoutineOccurrence; const cases = [
  () => ({ status: "available", routines: {} }),
  () => { const x = get.call(h.api.CandidateMoveRoutineSystem); x.routines.push(clone(x.routines[0])); return x; },
  () => { const x = get.call(h.api.CandidateMoveRoutineSystem); x.routines[0].candidateMoveId = "candidate_move_bad_x"; return x; },
  () => { const x = get.call(h.api.CandidateMoveRoutineSystem); x.routines[0].candidateMoveRevision = 99; return x; },
  () => { const x = get.call(h.api.CandidateMoveRoutineSystem); x.routines[0].action = "wrong"; return x; },
]; const saved = clone(h.api.founder.routines); for (const make of cases) { h.api.CandidateMoveRoutineSystem.getRoutines = make; assert.equal(candidate(h).status, "unavailable"); assert.deepEqual(clone(h.api.founder.routines), saved); } h.api.CandidateMoveRoutineSystem.getRoutines = get; for (const make of [() => ({ status: "unavailable" }), () => ({ status: "available", occurrence: "current", routineId: "wrong", occurrenceKey: "x", opensAt: asOf, closesAt: "2026-09-18T17:00:00.000Z" }), () => ({ status: "available", occurrence: "current", routineId: routine.id, occurrenceKey: "x", opensAt: "bad", closesAt: "bad" })]) { h.api.CandidateMoveRoutineSystem.getRoutineOccurrence = make; assert.equal(candidate(h).status, "unavailable"); } h.api.CandidateMoveRoutineSystem.getRoutineOccurrence = occurrence; });

test("exact-revision Situation relationship, identical action revision ordering, and owner-history inconsistency are explicit", () => { const { h, m, s } = setup(); h.api.CandidateMoveCommitmentSystem.createCommitment({ candidateMoveId: m.id, expectedCandidateMoveRevision: 1, window: { kind: "deadline", dueAt: "2026-09-30T19:00:00.000Z" } }); h.api.CandidateMoveSystem.correctCandidateMove({ id: m.id, expectedRevision: 1, action: "Send revised package." }); const output = candidate(h); assert.equal(output.candidates[0].situationId, s.id); assert.deepEqual(output.candidates.map((x) => x.candidateMoveRevision), [1, 2]); const history = h.api.CandidateMoveSystem.getCandidateMoveHistory; h.api.CandidateMoveSystem.getCandidateMoveHistory = () => ({ ...history.call(h.api.CandidateMoveSystem), situationId: "situation_bad_x" }); assert.equal(candidate(h).status, "unavailable"); h.api.CandidateMoveSystem.getCandidateMoveHistory = history;
  const current = h.api.CandidateMoveSystem.getCandidateMove; const commitments = h.api.CandidateMoveCommitmentSystem.getCommitments; const window = h.api.CandidateMoveCommitmentSystem.getCommitmentWindowState; const routines = h.api.CandidateMoveRoutineSystem.getRoutines; const moveState = h.api.MoveStateSystem.getMoveState; const id = m.id; h.api.CandidateMoveSystem.getCandidateMove = () => ({ status: "available", candidateMove: {}, current: { id, situationId: s.id, revision: 2, status: "active" } }); h.api.CandidateMoveSystem.getCandidateMoveHistory = () => ({ status: "available", id, situationId: s.id, revisions: [{ revision: 1, action: "Same text.", status: "active" }, { revision: 2, action: "Same text.", status: "active" }] }); h.api.MoveStateSystem.getMoveState = () => ({ status: "available", state: "clarify", candidateMoveId: id, candidateMoveRevision: 2, basis: { kind: "insufficient-operating-truth", references: [] } }); h.api.CandidateMoveCommitmentSystem.getCommitments = () => ({ status: "available", records: [{ id: "commitment_same_x", revision: 1, status: "active", candidateMoveId: id, candidateMoveRevision: 1, acceptedAction: "Same text.", window: { kind: "deadline", dueAt: "2026-09-30T19:00:00.000Z" } }] }); h.api.CandidateMoveCommitmentSystem.getCommitmentWindowState = () => ({ status: "available", id: "commitment_same_x", lifecycle: "active", dueAt: "2026-09-30T19:00:00.000Z", windowState: "open", evaluatedAt: asOf }); h.api.CandidateMoveRoutineSystem.getRoutines = () => ({ status: "available", routines: [] }); const identical = candidate(h); assert.deepEqual(identical.candidates.map((x) => [x.candidateMoveRevision, x.action]), [[1, "Same text."], [2, "Same text."]]); h.api.CandidateMoveSystem.getCandidateMove = current; h.api.CandidateMoveSystem.getCandidateMoveHistory = history; h.api.CandidateMoveCommitmentSystem.getCommitments = commitments; h.api.CandidateMoveCommitmentSystem.getCommitmentWindowState = window; h.api.CandidateMoveRoutineSystem.getRoutines = routines; h.api.MoveStateSystem.getMoveState = moveState; });

test("malformed persisted Context is irrelevant and Context getters are never invoked", () => { const { h } = setup(); h.api.founder.commanderContext = { malformed: true }; h.api.CommanderContextSystem.getContext = () => { throw new Error("Context must not be read"); }; h.api.CommanderContextSystem.getContextHistory = () => { throw new Error("Context must not be read"); }; assert.equal(candidate(h).status, "available"); });
test("Attention preserves complete owner temporal facts across wall-clock changes and rejects pre-lifecycle Routine reads", () => {
  const { h, m } = setup({ now: asOf });
  const commitment = h.api.CandidateMoveCommitmentSystem.createCommitment({ candidateMoveId: m.id, expectedCandidateMoveRevision: 1, window: { kind: "deadline", dueAt: "2026-09-18T09:00:00.000Z" } });
  const routine = h.api.CandidateMoveRoutineSystem.createRoutine({ candidateMoveId: m.id, expectedCandidateMoveRevision: 1, schedule });
  const before = JSON.stringify(h.api.founder); const operations = h.localStorage.operations.length;
  const window = h.api.CandidateMoveCommitmentSystem.getCommitmentWindowState({ id: commitment.id, asOf });
  const occurrence = h.api.CandidateMoveRoutineSystem.getRoutineOccurrence({ id: routine.id, asOf });
  assert.equal(window.status, "available"); assert.equal(occurrence.status, "available");
  const first = candidate(h); assert.equal(first.status, "available"); assert.equal(first.asOf, asOf);
  assert.deepEqual(clone(first.candidates[0].bases.slice(1)), [
    { kind: "commitment", commitmentId: commitment.id, commitmentRevision: 1, lifecycle: window.lifecycle, dueAt: window.dueAt, deadlineState: window.windowState },
    { kind: "routine-occurrence", routineId: routine.id, routineRevision: 1, occurrenceKey: occurrence.occurrenceKey, opensAt: occurrence.opensAt, closesAt: occurrence.closesAt },
  ]);
  h.clock.setTime("2099-01-01T00:00:00.000Z");
  assert.deepEqual(clone(candidate(h)), clone(first));
  const earlier = "2026-09-18T09:59:59.999Z";
  assert.deepEqual(clone(h.api.CandidateMoveRoutineSystem.getRoutineOccurrence({ id: routine.id, asOf: earlier })), { status: "unavailable", reason: "routine-occurrence-before-lifecycle" });
  assert.deepEqual(clone(h.api.AttentionCandidateSystem.getCandidates({ asOf: earlier })), { status: "unavailable", reason: "attention-candidate-routine-invalid" });
  assert.equal(JSON.stringify(h.api.founder), before); assert.equal(h.localStorage.operations.length, operations);
  assert.deepEqual(h.calls, { memory: 0, notification: 0, refresh: 0 });
});
