const test = require("node:test"); const assert = require("node:assert/strict"); const fs = require("node:fs"); const path = require("node:path"); const vm = require("node:vm");
const root = path.resolve(__dirname, ".."); const files = ["js/storage.js", "systems/commander.system.js", "systems/commander-attention-policy.system.js"]; const source = Object.fromEntries(files.map((file) => [file, fs.readFileSync(path.join(root, file), "utf8")])); const clone = (value) => JSON.parse(JSON.stringify(value));
function store(initial = {}, behavior = {}) { const values = new Map(Object.entries(initial)); const operations = []; return { get length() { return values.size; }, key(i) { return Array.from(values.keys())[i] || null; }, getItem(k) { operations.push(["get", k]); return values.has(k) ? values.get(k) : null; }, setItem(k, v) { operations.push(["set", k]); if (behavior.setItem) behavior.setItem(k, String(v), values); else values.set(k, String(v)); }, removeItem(k) { values.delete(k); }, values, operations }; }
function load({ initial = {}, behavior = {}, commander = true } = {}) { const localStorage = store(initial, behavior); const calls = { memory: 0, notification: 0, refresh: 0 }; const context = vm.createContext({ Date, Math, JSON, localStorage, sessionStorage: store(), console: { warn() {}, error() {} }, MemorySystem: { saveArtifact() { calls.memory += 1; } }, showNotification() { calls.notification += 1; }, refreshSession() { calls.refresh += 1; } }); vm.runInContext(source["js/storage.js"], context); if (commander) vm.runInContext(source["systems/commander.system.js"], context); vm.runInContext(source["systems/commander-attention-policy.system.js"], context); vm.runInContext(";globalThis.__api={founder,loadFounder,saveFounder,CommanderSystem:typeof CommanderSystem==='undefined'?null:CommanderSystem,CommanderAttentionPolicySystem};", context); return { api: context.__api, localStorage, calls }; }
function writes(h) { return h.localStorage.operations.filter(([type]) => type === "set").length; } function establish(h, rules = [["move.actionable"]], expectedRevision = 0) { return h.api.CommanderAttentionPolicySystem.establishAttentionPolicy({ rules, expectedRevision }); }

test("policy is absent until explicit authority and absent reads are zero-write", () => { const h = load(); h.api.loadFounder(); const p = h.api.CommanderAttentionPolicySystem; const before = writes(h); assert.equal(p.getAttentionPolicy().status, "absent"); assert.equal(p.getAttentionPolicyHistory().status, "absent"); assert.equal(writes(h), before); assert.equal(Object.hasOwn(h.api.founder, "attentionPolicy"), false); });

test("establish canonicalizes conditions/rules, generates IDs, and active empty policy is distinct", () => { const h = load(); h.api.loadFounder(); const p = h.api.CommanderAttentionPolicySystem; const policy = establish(h, [["routine.current"], ["commitment.deadline.passed", "move.actionable"]]); assert.equal(policy.revisions[0].provenance.operation, "establish"); assert.deepEqual(clone(policy.revisions[0].rules.map((r) => r.conditions)), [["move.actionable", "commitment.deadline.passed"], ["routine.current"]]); for (const rule of policy.revisions[0].rules) assert.match(rule.id, /^attention_rule_[a-z0-9]+_[a-z0-9]+$/); const empty = load(); empty.api.loadFounder(); establish(empty, []); const current = empty.api.CommanderAttentionPolicySystem.getAttentionPolicy().current; assert.equal(current.revision, 1); assert.equal(current.status, "active"); assert.deepEqual(clone(current.rules), []); assert.deepEqual(clone(current.provenance), { authority: "commander", operation: "establish" }); assert.notEqual(empty.api.CommanderAttentionPolicySystem.getAttentionPolicy().status, "absent"); });

test("rule schema rejects unknown, duplicate, oversized, duplicate-set, and caller object inputs", () => { const h = load(); h.api.loadFounder(); const p = h.api.CommanderAttentionPolicySystem; for (const rules of [[[]], [["bad"]], [["move.actionable", "move.actionable"]], [["move.actionable", "move.waiting", "move.hold", "move.clarify"]], [["move.actionable"], ["move.actionable"]], [{ id: "caller", conditions: ["move.actionable"] }]]) assert.throws(() => p.establishAttentionPolicy({ rules, expectedRevision: 0 })); assert.equal(Object.hasOwn(h.api.founder, "attentionPolicy"), false); });

test("replace snapshots full authority, identical replace is zero-write, clear follows Context no-op convention, and expected revisions are strict", () => { const h = load(); h.api.loadFounder(); const p = h.api.CommanderAttentionPolicySystem; establish(h, [["move.actionable"]]); const replaced = p.replaceAttentionPolicy({ rules: [["routine.current"]], expectedRevision: 1 }); assert.equal(replaced.revisions.length, 2); assert.deepEqual(clone(replaced.revisions[1].rules.map((r) => r.conditions)), [["routine.current"]]); assert.deepEqual(clone(replaced.revisions[0].rules.map((r) => r.conditions)), [["move.actionable"]]); const before = writes(h); const same = p.replaceAttentionPolicy({ rules: [["routine.current"]], expectedRevision: 2 }); assert.equal(same.revisions.length, 2); assert.equal(writes(h), before); assert.throws(() => p.replaceAttentionPolicy({ rules: [["routine.current"]], expectedRevision: 1 })); const cleared = p.clearAttentionPolicy({ expectedRevision: 2 }); assert.deepEqual(clone(cleared.revisions[2]), { revision: 3, status: "cleared", rules: null, provenance: { authority: "commander", operation: "clear" }, recordedAt: cleared.revisions[2].recordedAt }); const after = writes(h); assert.equal(p.clearAttentionPolicy({ expectedRevision: 3 }).revisions.length, 3); assert.equal(writes(h), after); assert.throws(() => p.clearAttentionPolicy({ expectedRevision: 2 })); const restored = establish(h, [], 3); assert.equal(restored.revisions[3].provenance.operation, "establish"); const absent = load(); absent.api.loadFounder(); const noWrites = writes(absent); assert.equal(absent.api.CommanderAttentionPolicySystem.clearAttentionPolicy({ expectedRevision: 0 }).status, "absent"); assert.equal(writes(absent), noWrites); });

test("strict persisted history rejects corruption without fallback and returns detached data", () => { const h = load(); h.api.loadFounder(); const p = h.api.CommanderAttentionPolicySystem; establish(h); const corruptions = [(x) => { x.extra = true; }, (x) => { x.revisions[0].extra = true; }, (x) => { x.revisions[0].provenance.extra = true; }, (x) => { x.revisions[0].rules[0].extra = true; }, (x) => { x.revisions[0].rules[0].conditions = ["bad"]; }, (x) => { x.revisions[0].rules[0].id = "bad"; }, (x) => { x.revisions[0].recordedAt = "bad"; }, (x) => { x.revisions[0].rules[0].priority = 1; }]; for (const mutate of corruptions) { const saved = clone(h.api.founder.attentionPolicy); mutate(h.api.founder.attentionPolicy); assert.equal(p.getAttentionPolicy().status, "unavailable"); h.api.founder.attentionPolicy = saved; } const current = p.getAttentionPolicy(); const history = p.getAttentionPolicyHistory(); current.current.rules[0].conditions[0] = "move.hold"; history.revisions[0].rules[0].conditions[0] = "move.hold"; assert.equal(h.api.founder.attentionPolicy.revisions[0].rules[0].conditions[0], "move.actionable"); });

test("publication is exact-true and PIH-safe, preserves live reference on failure, and honors primary/mirror ordering", () => { for (const confirmation of [false, null, undefined]) { const h = load(); h.api.loadFounder(); h.api.CommanderSystem.save = () => confirmation; assert.throws(() => establish(h)); assert.equal(Object.hasOwn(h.api.founder, "attentionPolicy"), false); } const missing = load({ commander: false }); missing.api.loadFounder(); assert.throws(() => establish(missing)); let primaryFail = false; const failed = load({ behavior: { setItem(key, value, values) { if (primaryFail && key === "digitalMikeyFounder") throw new Error("primary"); values.set(key, value); } } }); failed.api.loadFounder(); primaryFail = true; assert.throws(() => establish(failed), /primary/); assert.equal(Object.hasOwn(failed.api.founder, "attentionPolicy"), false); const pih = load({ initial: { digitalMikeyFounder: "{bad" } }); pih.api.loadFounder(); assert.throws(() => establish(pih), /storage/); const unsafe = load(); unsafe.api.loadFounder(); const beforeUnsafe = writes(unsafe); Object.defineProperty(unsafe.api.founder, "attentionPolicy", { configurable: true, set() { throw new Error("setter"); } }); assert.throws(() => establish(unsafe)); assert.equal(writes(unsafe), beforeUnsafe); let observed; let observe = false; let legacyFail = false; const mirror = load({ behavior: { setItem(key, value, values) { if (observe && key === "digitalMikeyFounder") observed = mirror.api.founder.attentionPolicy; if (legacyFail && key === "founder") throw new Error("legacy"); values.set(key, value); } } }); mirror.api.loadFounder(); observe = true; legacyFail = true; establish(mirror); assert.equal(observed, undefined); assert.equal(mirror.api.founder.attentionPolicy.revisions.length, 1); const live = mirror.api.founder.attentionPolicy; const snapshot = clone(live); mirror.api.CommanderSystem.save = () => { throw new Error("failed"); }; assert.throws(() => mirror.api.CommanderAttentionPolicySystem.replaceAttentionPolicy({ rules: [["routine.current"]], expectedRevision: 1 }), /failed/); assert.equal(mirror.api.founder.attentionPolicy, live); assert.deepEqual(clone(live), snapshot); });

test("policy reloads exactly and production owner has no evaluation or source side effects", () => { const h = load(); h.api.loadFounder(); establish(h, [["commitment.active"], ["move.waiting", "routine.current"]]); const before = clone(h.api.founder); h.api.saveFounder(); const second = load({ initial: { digitalMikeyFounder: h.localStorage.values.get("digitalMikeyFounder") } }); second.api.loadFounder(); assert.deepEqual(clone(second.api.founder.attentionPolicy), clone(h.api.founder.attentionPolicy)); assert.deepEqual(clone(h.api.founder), before); assert.deepEqual(h.calls, { memory: 0, notification: 0, refresh: 0 }); });

test("unsupported internal operation rejects after revision validation and before persistence or publication", () => { const h = load(); h.api.loadFounder(); const p = h.api.CommanderAttentionPolicySystem; const before = writes(h); assert.throws(() => p.mutate({ rules: [["move.actionable"]], expectedRevision: 0, operation: "invalid" }), /operation/); assert.equal(writes(h), before); assert.equal(Object.hasOwn(h.api.founder, "attentionPolicy"), false); assert.throws(() => p.mutate({ rules: [["move.actionable"]], expectedRevision: 1, operation: "invalid" }), /revision/); });

test("inherited and non-extensible absent destinations reject before save", () => { const inherited = load(); inherited.api.loadFounder(); let inheritedSaves = 0; inherited.api.CommanderSystem.save = () => { inheritedSaves += 1; return true; }; Object.setPrototypeOf(inherited.api.founder, Object.create(Object.getPrototypeOf(inherited.api.founder), { attentionPolicy: { value: null, writable: false } })); assert.throws(() => establish(inherited), /published safely/); assert.equal(inheritedSaves, 0); const sealed = load(); sealed.api.loadFounder(); let sealedSaves = 0; sealed.api.CommanderSystem.save = () => { sealedSaves += 1; return true; }; Object.preventExtensions(sealed.api.founder); assert.throws(() => establish(sealed), /published safely/); assert.equal(sealedSaves, 0); });

test("not-loaded storage blocks mutation before policy publication", () => { const h = load(); const before = writes(h); assert.throws(() => establish(h), /storage/); assert.equal(writes(h), before); assert.equal(Object.hasOwn(h.api.founder, "attentionPolicy"), false); });

test("persisted duplicate IDs, duplicate signatures, noncanonical order, invalid transitions, and newest corruption fail closed without fallback", () => { const h = load(); h.api.loadFounder(); const p = h.api.CommanderAttentionPolicySystem; establish(h, [["move.actionable"], ["routine.current"]]); const corruptions = [(x) => { x.revisions[0].rules[1].id = x.revisions[0].rules[0].id; }, (x) => { x.revisions[0].rules[1].conditions = ["move.actionable"]; }, (x) => { x.revisions[0].rules[0].conditions = ["commitment.active", "move.actionable"]; }, (x) => { x.revisions[0].rules.reverse(); }, (x) => { x.revisions.push({ revision: 2, status: "active", rules: [], provenance: { authority: "commander", operation: "establish" }, recordedAt: new Date().toISOString() }); }, (x) => { x.revisions.push({ revision: 2, status: "cleared", rules: null, provenance: { authority: "commander", operation: "clear" }, recordedAt: "bad" }); }]; for (const corrupt of corruptions) { const saved = clone(h.api.founder.attentionPolicy); corrupt(h.api.founder.attentionPolicy); assert.equal(p.getAttentionPolicy().status, "unavailable"); assert.equal(p.getAttentionPolicyHistory().status, "unavailable"); h.api.founder.attentionPolicy = saved; } });

test("replace and clear save failures preserve exact live policy references", () => { for (const action of ["replace", "clear"]) { const h = load(); h.api.loadFounder(); establish(h); const live = h.api.founder.attentionPolicy; const snapshot = clone(live); h.api.CommanderSystem.save = () => { throw new Error("failed"); }; if (action === "replace") assert.throws(() => h.api.CommanderAttentionPolicySystem.replaceAttentionPolicy({ rules: [["routine.current"]], expectedRevision: 1 }), /failed/); else assert.throws(() => h.api.CommanderAttentionPolicySystem.clearAttentionPolicy({ expectedRevision: 1 }), /failed/); assert.equal(h.api.founder.attentionPolicy, live); assert.deepEqual(clone(live), snapshot); } });

test("generated IDs are unique; no-op revisions validate first and preserve exact policy history", () => { const h = load(); h.api.loadFounder(); const p = h.api.CommanderAttentionPolicySystem; establish(h, [["move.actionable"], ["routine.current"]]); const original = h.api.founder.attentionPolicy; const ids = clone(original.revisions[0].rules.map((rule) => rule.id)); assert.equal(new Set(ids).size, ids.length); for (const id of ids) assert.match(id, /^attention_rule_[a-z0-9]+_[a-z0-9]+$/); const beforeReplace = writes(h); assert.throws(() => p.replaceAttentionPolicy({ rules: [["routine.current"], ["move.actionable"]], expectedRevision: 0 }), /revision/); const same = p.replaceAttentionPolicy({ rules: [["routine.current"], ["move.actionable"]], expectedRevision: 1 }); assert.equal(writes(h), beforeReplace); assert.equal(same.revisions.length, 1); assert.deepEqual(clone(same.revisions[0].rules.map((rule) => rule.id)), ids); const cleared = p.clearAttentionPolicy({ expectedRevision: 1 }); const beforeClear = writes(h); assert.throws(() => p.clearAttentionPolicy({ expectedRevision: 1 }), /revision/); const repeated = p.clearAttentionPolicy({ expectedRevision: 2 }); assert.equal(writes(h), beforeClear); assert.deepEqual(clone(repeated), clone(cleared)); const absent = load(); absent.api.loadFounder(); const beforeAbsent = writes(absent); assert.throws(() => absent.api.CommanderAttentionPolicySystem.clearAttentionPolicy({ expectedRevision: 1 }), /revision/); assert.equal(absent.api.CommanderAttentionPolicySystem.clearAttentionPolicy({ expectedRevision: 0 }).status, "absent"); assert.equal(writes(absent), beforeAbsent); });

test("active empty policy reloads distinctly from absent and cleared", () => { const h = load(); h.api.loadFounder(); establish(h, []); h.api.saveFounder(); const active = load({ initial: { digitalMikeyFounder: h.localStorage.values.get("digitalMikeyFounder") } }); active.api.loadFounder(); assert.deepEqual(clone(active.api.CommanderAttentionPolicySystem.getAttentionPolicy().current.rules), []); assert.equal(active.api.CommanderAttentionPolicySystem.getAttentionPolicy().current.status, "active"); h.api.CommanderAttentionPolicySystem.clearAttentionPolicy({ expectedRevision: 1 }); h.api.saveFounder(); const cleared = load({ initial: { digitalMikeyFounder: h.localStorage.values.get("digitalMikeyFounder") } }); cleared.api.loadFounder(); assert.equal(cleared.api.CommanderAttentionPolicySystem.getAttentionPolicy().current.status, "cleared"); assert.equal(cleared.api.CommanderAttentionPolicySystem.getAttentionPolicy().current.rules, null); const absent = load(); absent.api.loadFounder(); assert.equal(absent.api.CommanderAttentionPolicySystem.getAttentionPolicy().status, "absent"); });