const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs"); const path = require("node:path"); const vm = require("node:vm");
const root = path.resolve(__dirname, ".."); const files = ["js/storage.js", "systems/commander.system.js", "systems/situation.system.js", "systems/candidate-move.system.js", "systems/candidate-move-hold.system.js", "systems/candidate-move-dependency.system.js", "systems/candidate-move-availability.system.js", "systems/candidate-move-commitment.system.js", "systems/candidate-move-routine.system.js", "systems/commander-context.system.js", "systems/move-state.system.js"];
const source = Object.fromEntries(files.map((file) => [file, fs.readFileSync(path.join(root, file), "utf8")])); const clone = (v) => JSON.parse(JSON.stringify(v)); const schedule = { kind: "weekly-utc", weekday: 5, opensAtUtc: "09:00:00Z", closesAtUtc: "17:00:00Z" };
function storage(initial = {}, behavior = {}) { const values = new Map(Object.entries(initial)); const operations = []; return { get length() { return values.size; }, key(i) { return Array.from(values.keys())[i] || null; }, getItem(k) { operations.push(["get", k]); return values.has(k) ? values.get(k) : null; }, setItem(k, v) { operations.push(["set", k]); if (behavior.setItem) behavior.setItem(k, String(v), values); else values.set(k, String(v)); }, removeItem(k) { values.delete(k); }, values, operations }; }
function load({ initial = {}, behavior = {}, commander = true } = {}) { const localStorage = storage(initial, behavior); const calls = { memory: 0, notification: 0, refresh: 0 }; const context = vm.createContext({ Date, Math, JSON, localStorage, sessionStorage: storage(), console: { warn() {}, error() {} }, MemorySystem: { saveArtifact() { calls.memory += 1; } }, showNotification() { calls.notification += 1; }, refreshSession() { calls.refresh += 1; } }); for (const file of files) { if (file === "systems/commander.system.js" && !commander) continue; vm.runInContext(source[file], context, { filename: file }); } vm.runInContext(";globalThis.__api={founder,loadFounder,saveFounder,CommanderSystem:typeof CommanderSystem==='undefined'?null:CommanderSystem,SituationSystem,CandidateMoveSystem,CandidateMoveCommitmentSystem,CandidateMoveRoutineSystem,CommanderContextSystem,MoveStateSystem};", context); return { api: context.__api, localStorage, calls }; }
function setup(options = {}) { const h = load(options); h.api.loadFounder(); const situation = h.api.SituationSystem.createSituation({ subject: "Package", currentReality: "Ready." }); const move = h.api.CandidateMoveSystem.createCandidateMove({ situationId: situation.id, action: "Send package." }); return { h, situation, move }; } function writes(h) { return h.localStorage.operations.filter(([t]) => t === "set").length; }

test("Context is absent until explicit set; absence is unknown rather than Open", () => { const { h, situation, move } = setup(); const c = h.api.CommanderContextSystem; h.api.CandidateMoveCommitmentSystem.createCommitment({ candidateMoveId: move.id, expectedCandidateMoveRevision: 1, window: { kind: "deadline", dueAt: "2026-09-30T19:00:00.000Z" } }); h.api.CandidateMoveRoutineSystem.createRoutine({ candidateMoveId: move.id, expectedCandidateMoveRevision: 1, schedule }); assert.equal(c.getContext().status, "absent"); assert.deepEqual(clone(c.getSituationEligibility({ situationId: situation.id })), { status: "available", eligibility: "unknown", reason: "context-absent" }); });

test("scoped Context requires exactly one valid Situation and retains eligibility through correction and closure", () => { const { h, situation } = setup(); const c = h.api.CommanderContextSystem; for (const ids of [[], [situation.id, situation.id], ["bad"], ["situation_unknown_x"]]) assert.throws(() => c.setScopedContext({ situationIds: ids, expectedRevision: 0 })); const set = c.setScopedContext({ situationIds: [situation.id], expectedRevision: 0 }); assert.equal(set.revisions[0].provenance.operation, "set"); assert.equal(c.getSituationEligibility({ situationId: situation.id }).eligibility, "eligible"); h.api.SituationSystem.correctSituation({ id: situation.id, expectedRevision: 1, currentReality: "Changed." }); assert.equal(c.getSituationEligibility({ situationId: situation.id }).eligibility, "eligible"); h.api.SituationSystem.closeSituation({ id: situation.id, expectedRevision: 2 }); assert.equal(c.getSituationEligibility({ situationId: situation.id }).eligibility, "eligible"); });

test("Open is explicit and valid without Situation; lifecycle uses expected revision, switch, clear, and zero-write no-ops", () => { const empty = load(); empty.api.loadFounder(); const c = empty.api.CommanderContextSystem; const open = c.setOpenContext({ expectedRevision: 0 }); assert.equal(open.revisions[0].scope.mode, "open"); assert.equal(open.revisions[0].provenance.operation, "set"); const before = writes(empty); c.setOpenContext({ expectedRevision: 1 }); assert.equal(writes(empty), before); assert.throws(() => c.setOpenContext({ expectedRevision: 0 })); const cleared = c.clearContext({ expectedRevision: 1 }); assert.equal(cleared.revisions[1].status, "cleared"); assert.equal(cleared.revisions[1].scope, null); const after = writes(empty); c.clearContext({ expectedRevision: 2 }); assert.equal(writes(empty), after); assert.throws(() => c.clearContext({ expectedRevision: 1 })); const reset = c.setOpenContext({ expectedRevision: 2 }); assert.equal(reset.revisions[2].provenance.operation, "set"); const absent = load(); absent.api.loadFounder(); const noWrites = writes(absent); assert.equal(absent.api.CommanderContextSystem.clearContext({ expectedRevision: 0 }).status, "absent"); assert.equal(writes(absent), noWrites); });

test("Open eligibility validates requested Situation and Context reads/history are detached and write-free", () => { const { h, situation } = setup(); const c = h.api.CommanderContextSystem; c.setOpenContext({ expectedRevision: 0 }); const before = writes(h); assert.equal(c.getSituationEligibility({ situationId: situation.id }).eligibility, "eligible"); assert.equal(c.getSituationEligibility({ situationId: "situation_missing_x" }).status, "unavailable"); const read = c.getContext(); const history = c.getContextHistory(); read.current.scope.mode = "bad"; history.revisions[0].scope.mode = "bad"; assert.equal(h.api.founder.commanderContext.revisions[0].scope.mode, "open"); assert.equal(writes(h), before); });

test("strict Context history fails closed without fallback and validates historical scoped references", () => { const { h, situation } = setup(); const c = h.api.CommanderContextSystem; c.setScopedContext({ situationIds: [situation.id], expectedRevision: 0 }); c.setOpenContext({ expectedRevision: 1 }); for (const mutate of [(x) => { x.extra = true; }, (x) => { x.revisions[1].extra = true; }, (x) => { x.revisions[1].provenance.extra = true; }, (x) => { x.revisions[1].scope.extra = true; }, (x) => { x.revisions[1].recordedAt = "bad"; }, (x) => { x.revisions[1].status = "bad"; }]) { const saved = clone(h.api.founder.commanderContext); mutate(h.api.founder.commanderContext); assert.equal(c.getContext().status, "unavailable"); h.api.founder.commanderContext = saved; } h.api.founder.commanderContext.revisions[0].scope.situationIds[0] = "situation_missing_x"; assert.equal(c.getContext().status, "unavailable"); });

test("Context does not alter Move State, Commitment, Routine, or other live domain truth", () => { const { h, situation, move } = setup(); const commitment = h.api.CandidateMoveCommitmentSystem.createCommitment({ candidateMoveId: move.id, expectedCandidateMoveRevision: 1, window: { kind: "deadline", dueAt: "2026-09-30T19:00:00.000Z" } }); const routine = h.api.CandidateMoveRoutineSystem.createRoutine({ candidateMoveId: move.id, expectedCandidateMoveRevision: 1, schedule }); const refs = { situation: h.api.founder.situation, move: h.api.founder.candidateMove, commitments: clone(h.api.founder.commitments), routines: clone(h.api.founder.routines), state: clone(h.api.MoveStateSystem.getMoveState()), occurrence: clone(h.api.CandidateMoveRoutineSystem.getRoutineOccurrence({ id: routine.id, asOf: "2026-09-18T10:00:00.000Z" })) }; const c = h.api.CommanderContextSystem; c.setScopedContext({ situationIds: [situation.id], expectedRevision: 0 }); c.setOpenContext({ expectedRevision: 1 }); c.clearContext({ expectedRevision: 2 }); assert.equal(h.api.founder.situation, refs.situation); assert.equal(h.api.founder.candidateMove, refs.move); assert.deepEqual(clone(h.api.founder.commitments), refs.commitments); assert.deepEqual(clone(h.api.founder.routines), refs.routines); assert.deepEqual(clone(h.api.MoveStateSystem.getMoveState()), refs.state); assert.deepEqual(clone(h.api.CandidateMoveRoutineSystem.getRoutineOccurrence({ id: routine.id, asOf: "2026-09-18T10:00:00.000Z" })), refs.occurrence); assert.equal(commitment.id, refs.commitments.records[0].id); });

test("Context persistence requires exact confirmation and preserves old references on failure", () => { for (const result of [false, null, undefined]) { const { h } = setup(); h.api.CommanderSystem.save = () => result; assert.throws(() => h.api.CommanderContextSystem.setOpenContext({ expectedRevision: 0 })); assert.equal(Object.hasOwn(h.api.founder, "commanderContext"), false); } const { h } = setup(); const c = h.api.CommanderContextSystem; c.setOpenContext({ expectedRevision: 0 }); const live = h.api.founder.commanderContext; const snapshot = clone(live); h.api.CommanderSystem.save = () => { throw new Error("failed"); }; assert.throws(() => c.clearContext({ expectedRevision: 1 })); assert.equal(h.api.founder.commanderContext, live); assert.deepEqual(clone(live), snapshot); });

test("Context PIH, descriptor, primary-observation, mirror, missing save, switch failure, reload, and unrelated identity contracts hold", () => {
  const missing = load({ commander: false }); missing.api.loadFounder(); assert.throws(() => missing.api.CommanderContextSystem.setOpenContext({ expectedRevision: 0 }));
  let primaryFail = false; const failed = setup({ behavior: { setItem(k, v, values) { if (primaryFail && k === "digitalMikeyFounder") throw new Error("primary"); values.set(k, v); } } }); primaryFail = true; assert.throws(() => failed.h.api.CommanderContextSystem.setOpenContext({ expectedRevision: 0 }), /primary/); assert.equal(Object.hasOwn(failed.h.api.founder, "commanderContext"), false);
  const unsafe = setup(); const beforeUnsafe = writes(unsafe.h); Object.defineProperty(unsafe.h.api.founder, "commanderContext", { configurable: true, set() { throw new Error("setter"); } }); assert.throws(() => unsafe.h.api.CommanderContextSystem.setOpenContext({ expectedRevision: 0 })); assert.equal(writes(unsafe.h), beforeUnsafe);
  const pih = load({ initial: { digitalMikeyFounder: "{bad" } }); pih.api.loadFounder(); assert.throws(() => pih.api.CommanderContextSystem.setOpenContext({ expectedRevision: 0 }), /storage/);
  let observed; let observe = false; let legacyFail = false; const mirror = setup({ behavior: { setItem(k, v, values) { if (observe && k === "digitalMikeyFounder") observed = mirror.h.api.founder.commanderContext; if (legacyFail && k === "founder") throw new Error("legacy"); values.set(k, v); } } }); observe = true; legacyFail = true; const saved = mirror.h.api.CommanderContextSystem.setOpenContext({ expectedRevision: 0 }); assert.equal(observed, undefined); assert.equal(mirror.h.api.founder.commanderContext.revisions[0].revision, 1);
  const switched = setup(); const c = switched.h.api.CommanderContextSystem; c.setOpenContext({ expectedRevision: 0 }); const live = switched.h.api.founder.commanderContext; const history = clone(live); switched.h.api.CommanderSystem.save = () => { throw new Error("failed"); }; assert.throws(() => c.setScopedContext({ situationIds: [switched.situation.id], expectedRevision: 1 }), /failed/); assert.equal(switched.h.api.founder.commanderContext, live); assert.deepEqual(clone(live), history);
  const reload = setup(); const refs = { founder: reload.h.api.founder, situation: reload.h.api.founder.situation, move: reload.h.api.founder.candidateMove, profile: reload.h.api.founder.profile }; reload.h.api.CommanderContextSystem.setOpenContext({ expectedRevision: 0 }); assert.equal(reload.h.api.founder, refs.founder); assert.equal(reload.h.api.founder.situation, refs.situation); assert.equal(reload.h.api.founder.candidateMove, refs.move); assert.equal(reload.h.api.founder.profile, refs.profile); const second = load({ initial: { digitalMikeyFounder: reload.h.localStorage.values.get("digitalMikeyFounder") } }); second.api.loadFounder(); assert.deepEqual(clone(second.api.founder.commanderContext), clone(reload.h.api.founder.commanderContext)); assert.equal(saved.revisions[0].scope.mode, "open");
});