const test = require("node:test"); const assert = require("node:assert/strict"); const fs = require("node:fs"); const path = require("node:path"); const vm = require("node:vm");
const root = path.resolve(__dirname, ".."); const source = fs.readFileSync(path.join(root, "js/widgets/operating-setup.widget.js"), "utf8"); const index = fs.readFileSync(path.join(root, "index.html"), "utf8"); const styleSource = fs.readFileSync(path.join(root, "style.css"), "utf8"); const clone = (value) => JSON.parse(JSON.stringify(value)); const ownerFiles = ["js/storage.js", "systems/commander.system.js", "systems/situation.system.js", "systems/candidate-move.system.js", "systems/commander-context.system.js", "systems/commander-attention-policy.system.js"];
function element() { return { value: "", checked: false, textContent: "", hidden: false, disabled: false, handlers: {}, addEventListener(type, handler) { this.handlers[type] = handler; } }; }
function activeSituation(revision = 1, subject = "Package", currentReality = "Ready.") { return { status: "available", current: { id: "situation_a", revision, subject, currentReality, carryStatus: "active" } }; }
function activeMove(revision = 1, action = "Send package.") { return { status: "available", current: { id: "candidate_move_a", situationId: "situation_a", revision, action, status: "active" } }; }
function activeContext(revision = 1, mode = "open") { return { status: "available", current: { revision, status: "active", scope: mode === "open" ? { mode } : { mode, situationIds: ["situation_a"] } } }; }
function activePolicy(revision = 1) { return { status: "available", current: { revision, status: "active", rules: [{ id: "attention_rule_a_a", conditions: ["move.clarify"] }] } }; }
function harness({ situation = { status: "absent", situation: null }, move = { status: "absent", candidateMove: null }, context = { status: "absent" }, policy = { status: "absent" }, fail = {} } = {}) {
  const nodes = new Map(); const ids = ["operating-setup-status", "operating-setup-error", "operating-situation-current", "operating-situation-subject", "operating-situation-reality", "operating-situation-form", "operating-situation-subject-input", "operating-situation-reality-input", "operating-situation-submit", "operating-situation-edit", "operating-situation-close", "operating-move-current", "operating-move-absent", "operating-move-prerequisite", "operating-move-action", "operating-move-form", "operating-move-action-input", "operating-move-submit", "operating-move-edit", "operating-move-withdraw", "operating-context-current", "operating-context-scoped", "operating-context-open", "operating-context-clear", "operating-policy-clarify", "operating-policy-current", "operating-policy-submit", "operating-policy-clear", "operating-policy-guidance"]; ids.forEach((id) => nodes.set(id, element())); const calls = { situation: [], move: [], context: [], policy: [], saves: 0, storage: 0, other: 0 };
  const SituationSystem = { getSituation() { return clone(situation); }, createSituation(input) { calls.situation.push(["create", clone(input)]); if (fail.situation) throw new Error("Situation failed"); situation = activeSituation(1, input.subject, input.currentReality); }, correctSituation(input) { calls.situation.push(["correct", clone(input)]); situation = activeSituation(input.expectedRevision + 1, situation.current.subject, input.currentReality); }, closeSituation(input) { calls.situation.push(["close", clone(input)]); situation = { status: "available", current: { ...situation.current, revision: input.expectedRevision + 1, carryStatus: "closed" } }; } };
  const CandidateMoveSystem = { getCandidateMove() { return clone(move); }, createCandidateMove(input) { calls.move.push(["create", clone(input)]); if (fail.move) throw new Error("Move failed"); move = activeMove(1, input.action); }, correctCandidateMove(input) { calls.move.push(["correct", clone(input)]); move = activeMove(input.expectedRevision + 1, input.action); }, withdrawCandidateMove(input) { calls.move.push(["withdraw", clone(input)]); move = { status: "available", current: { ...move.current, revision: input.expectedRevision + 1, status: "withdrawn" } }; } };
  const CommanderContextSystem = { getContext() { return clone(context); }, setOpenContext(input) { calls.context.push(["open", clone(input)]); context = activeContext((context.current?.revision || 0) + 1); }, setScopedContext(input) { calls.context.push(["scoped", clone(input)]); context = activeContext((context.current?.revision || 0) + 1, "scoped"); }, clearContext(input) { calls.context.push(["clear", clone(input)]); context = { status: "available", current: { revision: input.expectedRevision + 1, status: "cleared" } }; } };
  const CommanderAttentionPolicySystem = { getAttentionPolicy() { return clone(policy); }, establishAttentionPolicy(input) { calls.policy.push(["establish", clone(input)]); policy = activePolicy((policy.current?.revision || 0) + 1); }, replaceAttentionPolicy(input) { calls.policy.push(["replace", clone(input)]); policy = activePolicy(input.expectedRevision + 1); }, clearAttentionPolicy(input) { calls.policy.push(["clear", clone(input)]); policy = { status: "available", current: { revision: input.expectedRevision + 1, status: "cleared" } }; } };
  const runtime = vm.createContext({ window: {}, document: { getElementById(id) { return nodes.get(id) || null; } }, SituationSystem, CandidateMoveSystem, CommanderContextSystem, CommanderAttentionPolicySystem, console: { warn() {}, error() {} } }); vm.runInContext(source, runtime); const fire = (id, type = "click") => nodes.get(id).handlers[type]({ preventDefault() {} }); return { nodes, calls, fire, state: () => ({ situation, move, context, policy }), widget: runtime.window.OperatingSetupWidget }; }

test("fresh render is incomplete, creates no authority, and exposes only bounded singleton setup copy", () => { const h = harness(); assert.equal(h.nodes.get("operating-setup-status").textContent, "Core operating setup incomplete"); assert.deepEqual(h.calls, { situation: [], move: [], context: [], policy: [], saves: 0, storage: 0, other: 0 }); assert.match(index, /Recorded Situation/); assert.match(index, /Current Move/); assert.doesNotMatch(index, /Add Situation|Add another move|backlog|portfolio|to-do/i); assert.match(index, /Show recorded moves that need more operating truth/); assert.doesNotMatch(index, /move\.actionable|move\.waiting|move\.hold|commitment\.active|routine\.current/); });

test("real fresh owner contracts are absent only after healthy Founder load and render as incomplete", () => { const values = new Map(); const localStorage = { get length() { return values.size; }, key(i) { return Array.from(values.keys())[i] || null; }, getItem(key) { return values.has(key) ? values.get(key) : null; }, setItem(key, value) { values.set(key, String(value)); }, removeItem(key) { values.delete(key); } }; const runtime = vm.createContext({ Date, Math, JSON, localStorage, console: { warn() {}, error() {} } }); for (const file of ownerFiles) vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), runtime, { filename: file }); vm.runInContext(";globalThis.__owners={loadFounder,SituationSystem,CandidateMoveSystem,CommanderContextSystem,CommanderAttentionPolicySystem};", runtime); assert.equal(runtime.__owners.SituationSystem.getSituation().status, "unavailable"); runtime.__owners.loadFounder(); const fresh = { situation: runtime.__owners.SituationSystem.getSituation(), move: runtime.__owners.CandidateMoveSystem.getCandidateMove(), context: runtime.__owners.CommanderContextSystem.getContext(), policy: runtime.__owners.CommanderAttentionPolicySystem.getAttentionPolicy() }; assert.deepEqual(clone(fresh), { situation: { status: "absent", situation: null }, move: { status: "absent", candidateMove: null }, context: { status: "absent" }, policy: { status: "absent" } }); const h = harness(fresh); assert.equal(h.nodes.get("operating-setup-status").textContent, "Core operating setup incomplete"); assert.match(h.nodes.get("operating-context-current").textContent, /No operating scope/); assert.match(h.nodes.get("operating-policy-current").textContent, /No Attention Policy/); assert.equal(h.nodes.get("operating-move-absent").hidden, false); assert.equal(h.nodes.get("operating-move-current").hidden, true); });
test("Current Move visibility requires an active Situation and an active Move", () => { const fresh = harness(); assert.equal(fresh.nodes.get("operating-move-absent").hidden, false); assert.equal(fresh.nodes.get("operating-move-current").hidden, true); assert.equal(fresh.nodes.get("operating-move-form").hidden, true); assert.equal(fresh.nodes.get("operating-move-prerequisite").hidden, false); const ready = harness({ situation: activeSituation() }); assert.equal(ready.nodes.get("operating-move-absent").hidden, false); assert.equal(ready.nodes.get("operating-move-current").hidden, true); assert.equal(ready.nodes.get("operating-move-form").hidden, false); assert.equal(ready.nodes.get("operating-move-prerequisite").hidden, true); const active = harness({ situation: activeSituation(), move: activeMove() }); assert.equal(active.nodes.get("operating-move-absent").hidden, true); assert.equal(active.nodes.get("operating-move-current").hidden, false); assert.equal(active.nodes.get("operating-move-form").hidden, true); assert.equal(active.nodes.get("operating-move-prerequisite").hidden, true); assert.match(styleSource, /\.operating-setup-card \[hidden\] \{ display: none !important; \}/); });

test("Situation and Current Move submit through owners with safe current bindings", () => { const h = harness(); h.nodes.get("operating-situation-subject-input").value = "<img src=x onerror=1>"; h.nodes.get("operating-situation-reality-input").value = "<script>bad()</script>"; h.fire("operating-situation-form", "submit"); assert.deepEqual(h.calls.situation, [["create", { subject: "<img src=x onerror=1>", currentReality: "<script>bad()</script>" }]]); assert.equal(h.nodes.get("operating-situation-subject").textContent, "<img src=x onerror=1>"); assert.equal(h.nodes.get("operating-situation-reality").textContent, "<script>bad()</script>"); h.nodes.get("operating-move-action-input").value = "Send it."; h.fire("operating-move-form", "submit"); assert.deepEqual(h.calls.move, [["create", { situationId: "situation_a", action: "Send it." }]]); assert.equal(h.nodes.get("operating-move-action").textContent, "Send it."); });

test("Current Situation is required for move creation and later failed move creation preserves earlier authority", () => { const absent = harness(); assert.equal(absent.nodes.get("operating-move-submit").disabled, true); const failed = harness({ situation: activeSituation(), fail: { move: true } }); failed.nodes.get("operating-move-action-input").value = "Try move."; failed.fire("operating-move-form", "submit"); assert.equal(failed.state().situation.current.subject, "Package"); assert.equal(failed.state().move.status, "absent"); assert.equal(failed.nodes.get("operating-setup-error").textContent, "Move failed"); });

test("Context establishes, switches, and clears with fresh revisions and exact current Situation binding", () => { const h = harness({ situation: activeSituation(), context: activeContext(4) }); h.fire("operating-context-scoped"); assert.deepEqual(h.calls.context[0], ["scoped", { situationIds: ["situation_a"], expectedRevision: 4 }]); h.fire("operating-context-open"); assert.deepEqual(h.calls.context[1], ["open", { expectedRevision: 5 }]); h.fire("operating-context-clear"); assert.deepEqual(h.calls.context[2], ["clear", { expectedRevision: 6 }]); });

test("Policy has no default or empty authority, maps only Clarify, replaces, and clears with fresh revisions", () => { const h = harness({ policy: { status: "absent" } }); h.fire("operating-policy-submit"); assert.deepEqual(h.calls.policy, []); assert.match(h.nodes.get("operating-policy-guidance").textContent, /Select at least one/); h.nodes.get("operating-policy-clarify").checked = true; h.fire("operating-policy-submit"); assert.deepEqual(h.calls.policy[0], ["establish", { rules: [["move.clarify"]], expectedRevision: 0 }]); h.fire("operating-policy-submit"); assert.deepEqual(h.calls.policy[1], ["replace", { rules: [["move.clarify"]], expectedRevision: 1 }]); h.fire("operating-policy-clear"); assert.deepEqual(h.calls.policy[2], ["clear", { expectedRevision: 2 }]); });

test("corrections, closure, withdrawal, unavailable, cleared, and reload rendering use owner truth", () => { const h = harness({ situation: activeSituation(3), move: activeMove(4), context: { status: "available", current: { revision: 2, status: "cleared" } }, policy: { status: "unavailable" } }); assert.match(h.nodes.get("operating-context-current").textContent, /cleared/); assert.match(h.nodes.get("operating-policy-current").textContent, /unavailable/); h.fire("operating-situation-edit"); h.nodes.get("operating-situation-reality-input").value = "Changed."; h.fire("operating-situation-form", "submit"); assert.deepEqual(h.calls.situation[0], ["correct", { id: "situation_a", expectedRevision: 3, currentReality: "Changed." }]); h.fire("operating-move-edit"); h.nodes.get("operating-move-action-input").value = "Changed move."; h.fire("operating-move-form", "submit"); assert.deepEqual(h.calls.move[0], ["correct", { id: "candidate_move_a", expectedRevision: 4, action: "Changed move." }]); h.fire("operating-move-withdraw"); assert.deepEqual(h.calls.move[1], ["withdraw", { id: "candidate_move_a", expectedRevision: 5 }]); assert.match(h.nodes.get("operating-move-action").textContent, /withdrawn/); h.fire("operating-situation-close"); assert.deepEqual(h.calls.situation[1], ["close", { id: "situation_a", expectedRevision: 4 }]); assert.match(h.nodes.get("operating-situation-reality").textContent, /closed/); h.widget.render(); assert.equal(h.nodes.get("operating-setup-status").textContent, "Unavailable"); });

test("widget source has no direct persistence, cross-domain, or briefing integration", () => { for (const pattern of [/founder\./, /localStorage/, /sessionStorage/, /CommanderSystem\.save/, /Mission/, /Profile/, /Evidence/, /Memory/, /Guidance/, /Decision/, /Briefing/, /Communication/, /Notification/]) assert.doesNotMatch(source, pattern); assert.match(index, /js\/widgets\/operating-setup\.widget\.js/); });