const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const root = path.resolve(__dirname, "..");
const systemFile = "systems/temporal-projection.system.js";
const ownerFiles = ["js/storage.js", "systems/commander.system.js", "systems/situation.system.js", "systems/candidate-move.system.js", "systems/candidate-move-hold.system.js", "systems/candidate-move-dependency.system.js", "systems/candidate-move-availability.system.js", "systems/candidate-move-commitment.system.js", "systems/candidate-move-routine.system.js", systemFile];
const source = Object.fromEntries(ownerFiles.map((file) => [file, fs.readFileSync(path.join(root, file), "utf8")]));
const clone = (value) => JSON.parse(JSON.stringify(value));
const from = "2026-09-14T00:00:00.000Z";
const to = "2026-09-28T00:00:00.000Z";

function clock(now = "2026-09-14T08:00:00.000Z") { let time = Date.parse(now); return class extends Date { constructor(...args) { super(...(args.length ? args : [time])); } static now() { return time; } static setTime(value) { time = Date.parse(value); } }; }
function store() { const values = new Map(); const operations = []; return { get length() { return values.size; }, key(index) { return Array.from(values.keys())[index] || null; }, getItem(key) { operations.push(["get", key]); return values.get(key) || null; }, setItem(key, value) { operations.push(["set", key]); values.set(key, String(value)); }, removeItem(key) { values.delete(key); }, values, operations }; }
function real({ now } = {}) { const DateClass = clock(now); const localStorage = store(); const context = vm.createContext({ Date: DateClass, Math, JSON, localStorage, sessionStorage: store(), console: { warn() {}, error() {} }, MemorySystem: { saveArtifact() {} }, showNotification() {}, refreshSession() {} }); for (const file of ownerFiles) vm.runInContext(source[file], context, { filename: file }); vm.runInContext(";globalThis.__api={founder,loadFounder,SituationSystem,CandidateMoveSystem,CandidateMoveCommitmentSystem,CandidateMoveRoutineSystem,TemporalProjectionSystem};", context); return { api: context.__api, localStorage, DateClass }; }
function setup(options = {}) { const h = real(options); h.api.loadFounder(); const situation = h.api.SituationSystem.createSituation({ subject: "Package", currentReality: "Ready." }); const move = h.api.CandidateMoveSystem.createCandidateMove({ situationId: situation.id, action: "Send package." }); return { h, move }; }
function stub({ commitments, routines, DateClass = Date } = {}) { const context = vm.createContext({ Date: DateClass, JSON, CandidateMoveCommitmentSystem: commitments, CandidateMoveRoutineSystem: routines, console: { warn() {}, error() {} } }); vm.runInContext(source[systemFile], context, { filename: systemFile }); vm.runInContext(";globalThis.__api=TemporalProjectionSystem;", context); return context.__api; }
function commitment(overrides = {}) { return { id: "commitment_test_aaa", revision: 1, status: "active", candidateMoveId: "candidate_move_test_aaa", candidateMoveRevision: 1, acceptedAction: "Send package.", window: { kind: "deadline", dueAt: "2026-09-15T10:00:00.000Z" }, ...overrides }; }
function routine(overrides = {}) { return { id: "routine_test_aaa", candidateMoveId: "candidate_move_test_aaa", candidateMoveRevision: 1, action: "Send package.", lifecycle: "active", schedule: { kind: "weekly-utc", weekday: 1, opensAtUtc: "09:00:17Z", closesAtUtc: "10:00:43Z" }, revisions: [{ revision: 1, status: "active", schedule: { kind: "weekly-utc", weekday: 1, opensAtUtc: "09:00:17Z", closesAtUtc: "10:00:43Z" }, recordedAt: "2026-09-01T00:00:00.000Z" }], ...overrides }; }
function routineOwner(records, occurrence = ({ id, asOf }) => { const r = records.find((item) => item.id === id); const date = new Date(asOf); const day = date.toISOString().slice(0, 10); return { status: "available", occurrence: "current", routineId: id, occurrenceKey: `${id}:${day}`, scheduledDateUtc: day, opensAt: `${day}T${r.schedule.opensAtUtc.slice(0, 8)}.000Z`, closesAt: `${day}T${r.schedule.closesAtUtc.slice(0, 8)}.000Z` }; }) { return { getRoutines() { return { status: "available", routines: clone(records) }; }, getRoutineOccurrence: occurrence }; }

test("range validation is exact, bounded, and performs zero owner reads", () => {
  let reads = 0; const api = stub({ commitments: { getCommitments() { reads += 1; return { status: "absent" }; } }, routines: { getRoutines() { reads += 1; return { status: "absent" }; }, getRoutineOccurrence() { reads += 1; } } });
  for (const [label, input] of [["null", null], ["missing both", {}], ["missing from", { to }], ["missing to", { from }], ["milliseconds missing", { from: "2026-09-14T00:00:00Z", to }], ["offset", { from: "2026-09-14T00:00:00.000+00:00", to }], ["impossible date", { from: "2026-02-30T00:00:00.000Z", to }], ["equal", { from, to: from }], ["reversed", { from: to, to: from }]]) { const result = api.getProjection(input); assert.equal(result.status, "unavailable", label); assert.equal(result.reason, "temporal-projection-range-invalid", label); assert.equal(result.range, null, label); assert.deepEqual(clone(result.sources), { commitments: { status: "not-read", reason: null }, routines: { status: "not-read", reason: null } }, label); }
  assert.equal(reads, 0); assert.equal(api.getProjection({ from, to }).status, "available"); assert.equal(reads, 2); assert.equal(api.getProjection({ from, to: "2026-09-28T00:00:00.001Z" }).reason, "temporal-projection-range-too-large"); assert.equal(reads, 2);
});

test("Commitments use active accepted deadline truth with [from,to) boundaries and no fabricated fields", () => {
  const { h, move } = setup(); const owner = h.api.CandidateMoveCommitmentSystem;
  const make = (dueAt) => owner.createCommitment({ candidateMoveId: move.id, expectedCandidateMoveRevision: 1, window: { kind: "deadline", dueAt } });
  const first = make("2026-09-14T00:00:00.000Z"); owner.completeCommitment({ id: first.id, expectedRevision: 1 }); const second = make("2026-09-15T10:00:00.000Z"); owner.cancelCommitment({ id: second.id, expectedRevision: 1 }); const active = make("2026-09-21T10:00:00.000Z");
  h.api.CandidateMoveSystem.correctCandidateMove({ id: move.id, expectedRevision: 1, action: "Corrected." }); h.api.CandidateMoveSystem.withdrawCandidateMove({ id: move.id, expectedRevision: 2 });
  const projection = h.api.TemporalProjectionSystem.getProjection({ from: "2026-09-14T00:00:00.000Z", to: "2026-09-21T10:00:00.001Z" }); const item = projection.items.find((value) => value.sourceId === active.id);
  assert.deepEqual(clone(item), { kind: "commitment-deadline", sourceId: active.id, sourceRevision: 1, candidateMoveId: move.id, candidateMoveRevision: 1, action: "Send package.", occursAt: "2026-09-21T10:00:00.000Z" }); assert.equal(Object.hasOwn(item, "duration"), false); assert.equal(projection.items.length, 1);
});

test("Commitment exact boundaries include from, exclude before/from-to end", () => {
  const records = [commitment({ id: "commitment_test_before", window: { kind: "deadline", dueAt: "2026-09-13T23:59:59.999Z" } }), commitment({ id: "commitment_test_from", window: { kind: "deadline", dueAt: from } }), commitment({ id: "commitment_test_inside", window: { kind: "deadline", dueAt: "2026-09-20T00:00:00.000Z" } }), commitment({ id: "commitment_test_to", window: { kind: "deadline", dueAt: to } })];
  const api = stub({ commitments: { getCommitments() { return { status: "available", records }; } }, routines: { getRoutines() { return { status: "absent" }; }, getRoutineOccurrence() {} } }); assert.deepEqual(api.getProjection({ from, to }).items.map((x) => x.sourceId), ["commitment_test_from", "commitment_test_inside"]);
});

test("Routine UTC candidates honor inclusive closing, exclusive opening at to, full bounds, seconds, and calendar boundaries", () => {
  const records = [routine({ schedule: { kind: "weekly-utc", weekday: 6, opensAtUtc: "00:00:17Z", closesAtUtc: "01:00:43Z" }, revisions: [{ revision: 1, status: "active", schedule: { kind: "weekly-utc", weekday: 6, opensAtUtc: "00:00:17Z", closesAtUtc: "01:00:43Z" }, recordedAt: "2020-01-01T00:00:00.000Z" }] }), routine({ id: "routine_test_sunday", schedule: { kind: "weekly-utc", weekday: 7, opensAtUtc: "23:00:00Z", closesAtUtc: "23:59:59Z" }, revisions: [{ revision: 1, status: "active", schedule: { kind: "weekly-utc", weekday: 7, opensAtUtc: "23:00:00Z", closesAtUtc: "23:59:59Z" }, recordedAt: "2020-01-01T00:00:00.000Z" }] })]; const occurrence = ({ id, asOf }) => { const record = records.find((item) => item.id === id); const date = new Date(asOf); const offset = ((date.getUTCDay() + 6) % 7) + 1 === record.schedule.weekday ? 0 : -86400000; const day = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()) + offset).toISOString().slice(0, 10); return { status: "available", occurrence: "current", routineId: id, occurrenceKey: `${id}:${day}`, scheduledDateUtc: day, opensAt: `${day}T${record.schedule.opensAtUtc.slice(0, 8)}.000Z`, closesAt: `${day}T${record.schedule.closesAtUtc.slice(0, 8)}.000Z` }; }; const api = stub({ commitments: { getCommitments() { return { status: "absent" }; } }, routines: routineOwner(records, occurrence) });
  const projection = api.getProjection({ from: "2026-09-12T01:00:43.000Z", to: "2026-09-26T00:00:17.000Z" }); assert.deepEqual(projection.items.map((x) => [x.sourceId, x.opensAt, x.closesAt]), [["routine_test_aaa", "2026-09-12T00:00:17.000Z", "2026-09-12T01:00:43.000Z"], ["routine_test_sunday", "2026-09-13T23:00:00.000Z", "2026-09-13T23:59:59.000Z"], ["routine_test_aaa", "2026-09-19T00:00:17.000Z", "2026-09-19T01:00:43.000Z"], ["routine_test_sunday", "2026-09-20T23:00:00.000Z", "2026-09-20T23:59:59.000Z"]]);
  const year = api.getProjection({ from: "2025-12-28T00:00:00.000Z", to: "2026-01-05T00:00:00.000Z" }); assert.equal(year.items[0].opensAt, "2025-12-28T23:00:00.000Z"); const leap = api.getProjection({ from: "2024-02-25T00:00:00.000Z", to: "2024-03-04T00:00:00.000Z" }); assert.equal(leap.items.length, 3);
});

test("Routine owner integration enforces paused, retired, withdrawn, stale revision, and lifecycle witness behavior", () => {
  const { h, move } = setup({ now: "2026-09-14T09:30:17.000Z" }); const owner = h.api.CandidateMoveRoutineSystem; const schedule = { kind: "weekly-utc", weekday: 1, opensAtUtc: "09:00:17Z", closesAtUtc: "10:00:43Z" }; const created = owner.createRoutine({ candidateMoveId: move.id, expectedCandidateMoveRevision: 1, schedule });
  let result = h.api.TemporalProjectionSystem.getProjection({ from: "2026-09-14T00:00:00.000Z", to: "2026-09-15T00:00:00.000Z" }); assert.equal(result.items.length, 1); assert.equal(result.items[0].opensAt, "2026-09-14T09:00:17.000Z"); owner.pauseRoutine({ id: created.id, expectedRevision: 1 }); assert.equal(h.api.TemporalProjectionSystem.getProjection({ from, to: "2026-09-15T00:00:00.000Z" }).items.length, 0); owner.resumeRoutine({ id: created.id, expectedRevision: 2 }); assert.equal(h.api.TemporalProjectionSystem.getProjection({ from, to: "2026-09-15T00:00:00.000Z" }).items.length, 1); owner.retireRoutine({ id: created.id, expectedRevision: 3 }); assert.equal(h.api.TemporalProjectionSystem.getProjection({ from, to: "2026-09-15T00:00:00.000Z" }).items.length, 0); const replacement = owner.createRoutine({ candidateMoveId: move.id, expectedCandidateMoveRevision: 1, schedule }); assert.equal(h.api.TemporalProjectionSystem.getProjection({ from, to: "2026-09-15T00:00:00.000Z" }).items.length, 1); h.api.CandidateMoveSystem.correctCandidateMove({ id: move.id, expectedRevision: 1, action: "Corrected." }); assert.equal(h.api.TemporalProjectionSystem.getProjection({ from, to }).items.length, 0); h.api.CandidateMoveSystem.withdrawCandidateMove({ id: move.id, expectedRevision: 2 }); assert.equal(h.api.TemporalProjectionSystem.getProjection({ from, to }).items.length, 0); assert.ok(replacement.id);
});

test("Routine witnesses are explicit and owner consistency failures discard the whole Routine source", () => {
  const records = [routine(), routine({ id: "routine_test_bbb" })]; const witnesses = []; const api = stub({ commitments: { getCommitments() { return { status: "available", records: [commitment({ window: { kind: "deadline", dueAt: "2026-09-14T08:00:00.000Z" } })] }; } }, routines: routineOwner(records, ({ id, asOf }) => { witnesses.push({ id, asOf }); if (id === "routine_test_bbb") return { status: "available", occurrence: "current", routineId: id, occurrenceKey: `${id}:2026-09-14`, opensAt: "2026-09-14T09:00:17.000Z", closesAt: "2026-09-14T10:00:44.000Z" }; return { status: "available", occurrence: "current", routineId: id, occurrenceKey: `${id}:2026-09-14`, opensAt: "2026-09-14T09:00:17.000Z", closesAt: "2026-09-14T10:00:43.000Z" }; }) });
  const result = api.getProjection({ from, to: "2026-09-15T00:00:00.000Z" }); assert.equal(result.status, "partial"); assert.equal(result.sources.routines.reason, "temporal-projection-routines-occurrence-inconsistent"); assert.deepEqual(result.items.map((item) => item.kind), ["commitment-deadline"]); assert.equal(result.items.some((item) => item.kind === "routine-occurrence"), false); assert.equal(witnesses.length, 2); assert.ok(witnesses.every(({ asOf }) => typeof asOf === "string" && asOf <= "2026-09-14T10:00:43.000Z"));
});

test("Routine none responses require the authoritative matching id and witness", () => {
  const records = [routine()]; const validCommitments = { getCommitments() { return { status: "available", records: [commitment({ window: { kind: "deadline", dueAt: "2026-09-14T08:00:00.000Z" } })] }; } };
  const valid = stub({ commitments: validCommitments, routines: routineOwner(records, ({ id, asOf }) => ({ status: "available", occurrence: "none", id, evaluatedAt: asOf })) }).getProjection({ from, to: "2026-09-15T00:00:00.000Z" }); assert.equal(valid.status, "available"); assert.equal(valid.sources.routines.status, "available"); assert.deepEqual(valid.items.map((item) => item.kind), ["commitment-deadline"]);
  for (const response of [({ asOf }) => ({ status: "available", occurrence: "none", id: "routine_test_wrong", evaluatedAt: asOf }), ({ id }) => ({ status: "available", occurrence: "none", id, evaluatedAt: "2026-09-14T09:00:18.000Z" }), ({ id }) => ({ status: "available", occurrence: "none", id })]) { const result = stub({ commitments: validCommitments, routines: routineOwner(records, response) }).getProjection({ from, to: "2026-09-15T00:00:00.000Z" }); assert.equal(result.status, "partial"); assert.equal(result.sources.routines.status, "unavailable"); assert.equal(result.sources.routines.reason, "temporal-projection-routines-occurrence-inconsistent"); assert.deepEqual(result.items.map((item) => item.kind), ["commitment-deadline"]); }
});

test("Routine recurrence preserves canonical year 0099 and confirms the expected owner candidate", () => {
  const earlyFrom = "0099-01-04T00:00:00.000Z"; const earlyTo = "0099-01-05T00:00:00.000Z"; const earlyRoutine = routine({ schedule: { kind: "weekly-utc", weekday: 7, opensAtUtc: "09:00:17Z", closesAtUtc: "10:00:43Z" }, revisions: [{ revision: 1, status: "active", schedule: { kind: "weekly-utc", weekday: 7, opensAtUtc: "09:00:17Z", closesAtUtc: "10:00:43Z" }, recordedAt: "0099-01-01T00:00:00.000Z" }] }); const calls = [];
  const result = stub({ commitments: { getCommitments() { return { status: "absent" }; } }, routines: routineOwner([earlyRoutine], ({ id, asOf }) => { calls.push({ id, asOf }); return { status: "available", occurrence: "current", routineId: id, occurrenceKey: "routine_test_aaa:0099-01-04", scheduledDateUtc: "0099-01-04", opensAt: "0099-01-04T09:00:17.000Z", closesAt: "0099-01-04T10:00:43.000Z" }; }) }).getProjection({ from: earlyFrom, to: earlyTo });
  assert.equal(result.status, "available"); assert.deepEqual(result.items.map((item) => item.opensAt), ["0099-01-04T09:00:17.000Z"]); assert.deepEqual(calls, [{ id: "routine_test_aaa", asOf: "0099-01-04T09:00:17.000Z" }]);
});

test("each malformed current occurrence and every absent-source permutation preserve the envelope contract", () => {
  const records = [routine()]; const validCommitments = { getCommitments() { return { status: "available", records: [commitment({ window: { kind: "deadline", dueAt: "2026-09-14T08:00:00.000Z" } })] }; } };
  for (const occurrence of [
    { status: "available", occurrence: "current", routineId: "routine_test_other", occurrenceKey: "routine_test_aaa:2026-09-14", opensAt: "2026-09-14T09:00:17.000Z", closesAt: "2026-09-14T10:00:43.000Z" },
    { status: "available", occurrence: "current", routineId: "routine_test_aaa", occurrenceKey: "wrong", opensAt: "2026-09-14T09:00:17.000Z", closesAt: "2026-09-14T10:00:43.000Z" },
    { status: "available", occurrence: "current", routineId: "routine_test_aaa", occurrenceKey: "routine_test_aaa:2026-09-14", opensAt: "bad", closesAt: "2026-09-14T10:00:43.000Z" },
    { status: "available", occurrence: "current", routineId: "routine_test_aaa", occurrenceKey: "routine_test_aaa:2026-09-14", opensAt: "2026-09-14T09:00:17.000Z", closesAt: "2026-09-14T10:00:44.000Z" },
  ]) { const result = stub({ commitments: validCommitments, routines: routineOwner(records, () => occurrence) }).getProjection({ from, to: "2026-09-15T00:00:00.000Z" }); assert.equal(result.status, "partial"); assert.equal(result.sources.routines.reason, "temporal-projection-routines-occurrence-inconsistent"); assert.equal(result.items.length, 1); }
  const bothAbsent = stub({ commitments: { getCommitments() { return { status: "absent" }; } }, routines: { getRoutines() { return { status: "absent" }; }, getRoutineOccurrence() {} } }).getProjection({ from, to }); assert.equal(bothAbsent.status, "available"); assert.deepEqual(bothAbsent.items, []);
  const commitmentsAbsent = stub({ commitments: { getCommitments() { return { status: "absent" }; } }, routines: routineOwner(records) }).getProjection({ from, to: "2026-09-15T00:00:00.000Z" }); assert.equal(commitmentsAbsent.status, "available"); assert.equal(commitmentsAbsent.items.length, 1);
  const routinesAbsent = stub({ commitments: validCommitments, routines: { getRoutines() { return { status: "absent" }; }, getRoutineOccurrence() {} } }).getProjection({ from, to: "2026-09-15T00:00:00.000Z" }); assert.equal(routinesAbsent.status, "available"); assert.equal(routinesAbsent.items.length, 1);
});

test("source absence, independent failures, malformed truth, duplicates, ordering, and detachment are deterministic", () => {
  const validRoutines = [routine()]; const validCommitments = [commitment({ id: "commitment_test_bbb", window: { kind: "deadline", dueAt: "2026-09-14T09:00:17.000Z" } })];
  const available = stub({ commitments: { getCommitments() { return { status: "available", records: validCommitments }; } }, routines: routineOwner(validRoutines) }); const first = available.getProjection({ from, to: "2026-09-15T00:00:00.000Z" }); assert.deepEqual(first.items.map((x) => x.kind), ["commitment-deadline", "routine-occurrence"]); first.items.push({}); first.items[0].action = "mutated"; first.range.from = "bad"; first.sources.commitments.status = "bad"; const second = available.getProjection({ from, to: "2026-09-15T00:00:00.000Z" }); assert.equal(second.items.length, 2); assert.equal(second.items[0].action, "Send package."); assert.equal(second.range.from, from); assert.equal(second.sources.commitments.status, "available");
  const partial = stub({ commitments: { getCommitments() { throw new Error("no"); } }, routines: routineOwner(validRoutines) }).getProjection({ from, to: "2026-09-15T00:00:00.000Z" }); assert.equal(partial.status, "partial"); assert.equal(partial.sources.commitments.reason, "temporal-projection-commitments-reader-threw"); assert.equal(partial.items.length, 1);
  const unavailable = stub({ commitments: {}, routines: {} }).getProjection({ from, to }); assert.deepEqual(clone(unavailable), { status: "unavailable", range: { from, to }, reason: "temporal-projection-sources-unavailable", sources: { commitments: { status: "unavailable", reason: "temporal-projection-commitments-reader-missing" }, routines: { status: "unavailable", reason: "temporal-projection-routines-reader-missing" } }, items: [] });
  const corrupt = stub({ commitments: { getCommitments() { return { status: "available", records: [commitment(), commitment()] }; } }, routines: routineOwner(validRoutines) }).getProjection({ from, to }); assert.equal(corrupt.status, "partial"); assert.equal(corrupt.sources.commitments.reason, "temporal-projection-commitments-duplicate");
});

test("projection has no write, event, timer, clock-default, local-time, or presentation dependencies", () => {
  const text = source[systemFile]; assert.doesNotMatch(text, /Date\.now|new Date\(\)|localStorage|CommanderSystem|setTimeout|setInterval|dispatchEvent|localeCompare|urgency|priority|recommendation/); const before = JSON.stringify(routine()); const records = [routine()]; const api = stub({ commitments: { getCommitments() { return { status: "absent" }; } }, routines: routineOwner(records) }); api.getProjection({ from, to: "2026-09-15T00:00:00.000Z" }); assert.equal(JSON.stringify(records[0]), before);
});