// =====================================================
// FOUNDEROS
// ATTENTION CANDIDATE SYSTEM
// Read-only exact Candidate Move revision normalization.
// =====================================================

const AttentionCandidateSystem = {
  UTC_PATTERN: /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/,
  clone(value) { return JSON.parse(JSON.stringify(value)); },
  canonicalUtc(value) { return typeof value === "string" && this.UTC_PATTERN.test(value) && !Number.isNaN(new Date(value).getTime()) && new Date(value).toISOString() === value; },
  unavailable(reason) { return { status: "unavailable", reason }; },
  owner(name, methods) { const value = name === "CandidateMoveSystem" ? (typeof CandidateMoveSystem === "undefined" ? null : CandidateMoveSystem) : name === "MoveStateSystem" ? (typeof MoveStateSystem === "undefined" ? null : MoveStateSystem) : name === "CandidateMoveCommitmentSystem" ? (typeof CandidateMoveCommitmentSystem === "undefined" ? null : CandidateMoveCommitmentSystem) : name === "CandidateMoveRoutineSystem" ? (typeof CandidateMoveRoutineSystem === "undefined" ? null : CandidateMoveRoutineSystem) : null; return value && methods.every((method) => typeof value[method] === "function") ? value : null; },
  moveTruth() {
    const owner = this.owner("CandidateMoveSystem", ["getCandidateMove", "getCandidateMoveHistory"]); if (!owner) return null;
    const move = owner.getCandidateMove(); const history = owner.getCandidateMoveHistory();
    if (!move || !history || !["available", "absent"].includes(move.status) || move.status !== history.status) return null;
    if (move.status === "absent") return { move, history, actions: new Map() };
    if (!move.current || !move.candidateMove || !Array.isArray(history.revisions) || move.current.id !== history.id || move.current.situationId !== history.situationId || typeof move.current.id !== "string" || typeof move.current.situationId !== "string" || !Number.isInteger(move.current.revision) || !["active", "withdrawn"].includes(move.current.status)) return null;
    const actions = new Map(); for (const revision of history.revisions) { if (!revision || !Number.isInteger(revision.revision) || typeof revision.action !== "string" || !["active", "withdrawn"].includes(revision.status)) return null; if (revision.status === "active") actions.set(revision.revision, revision.action); }
    return { move, history, actions, relationships: new Map([[history.id, history.situationId]]) };
  },
  actionFor(truth, id, revision) { return truth.move.status === "available" && truth.move.current.id === id && truth.actions.get(revision) || null; },
  situationFor(truth, id) { return truth.relationships && truth.relationships.get(id) || null; },
  add(groups, id, revision, situationId, action, basis) { const key = `${id}\u0000${revision}`; let candidate = groups.get(key); if (!candidate) { candidate = { candidateMoveId: id, candidateMoveRevision: revision, situationId, action, bases: [] }; groups.set(key, candidate); } if (candidate.situationId !== situationId || candidate.action !== action || candidate.bases.some((item) => (item.kind === basis.kind && (item.kind === "move" || item.commitmentId === basis.commitmentId || item.routineId === basis.routineId)))) return false; candidate.bases.push(basis); return true; },
  getCandidates({ asOf } = {}) {
    if (!this.canonicalUtc(asOf)) return this.unavailable("attention-candidate-as-of-invalid");
    let truth; try { truth = this.moveTruth(); } catch (error) { return this.unavailable("attention-candidate-source-unavailable"); } if (!truth) return this.unavailable("attention-candidate-move-unavailable");
    const moveStateOwner = this.owner("MoveStateSystem", ["getMoveState"]); const commitmentOwner = this.owner("CandidateMoveCommitmentSystem", ["getCommitments", "getCommitmentWindowState"]); const routineOwner = this.owner("CandidateMoveRoutineSystem", ["getRoutines", "getRoutineOccurrence"]); if (!moveStateOwner || !commitmentOwner || !routineOwner) return this.unavailable("attention-candidate-source-unavailable");
    const groups = new Map();
    try {
      const state = moveStateOwner.getMoveState(); if (!state || !["available", "not-applicable", "unavailable"].includes(state.status)) return this.unavailable("attention-candidate-move-state-invalid");
      if (state.status === "unavailable") return this.unavailable("attention-candidate-move-state-unavailable");
      if (state.status === "not-applicable") { if (truth.move.status === "available" && truth.move.current.status === "active") return this.unavailable("attention-candidate-move-state-inconsistent"); }
      else { const expected = { actionable: "availability", waiting: "dependency", hold: "hold", clarify: "insufficient-operating-truth" }; const situationId = this.situationFor(truth, state.candidateMoveId); if (!expected[state.state] || !state.basis || state.basis.kind !== expected[state.state] || !Array.isArray(state.basis.references) || truth.move.status !== "available" || truth.move.current.status !== "active" || state.candidateMoveId !== truth.move.current.id || state.candidateMoveRevision !== truth.move.current.revision || !situationId) return this.unavailable("attention-candidate-move-state-invalid"); if (!this.add(groups, state.candidateMoveId, state.candidateMoveRevision, situationId, this.actionFor(truth, state.candidateMoveId, state.candidateMoveRevision), { kind: "move", moveState: state.state, stateBasis: this.clone(state.basis) })) return this.unavailable("attention-candidate-source-duplicate"); }
      const commitments = commitmentOwner.getCommitments(); if (!commitments || !["available", "absent"].includes(commitments.status)) return this.unavailable("attention-candidate-commitment-unavailable");
      if (commitments.status === "available") { if (!Array.isArray(commitments.records)) return this.unavailable("attention-candidate-commitment-invalid"); const ids = new Set(); for (const record of commitments.records) { if (!record || typeof record.id !== "string" || ids.has(record.id) || !Number.isInteger(record.revision) || !Number.isInteger(record.candidateMoveRevision) || typeof record.candidateMoveId !== "string" || typeof record.acceptedAction !== "string" || !["active", "completed", "canceled"].includes(record.status)) return this.unavailable("attention-candidate-commitment-invalid"); ids.add(record.id); if (record.status !== "active") continue; const action = this.actionFor(truth, record.candidateMoveId, record.candidateMoveRevision); const situationId = this.situationFor(truth, record.candidateMoveId); if (!action || !situationId || action !== record.acceptedAction || !record.window || record.window.kind !== "deadline" || !this.canonicalUtc(record.window.dueAt)) return this.unavailable("attention-candidate-commitment-invalid"); const window = commitmentOwner.getCommitmentWindowState({ id: record.id, asOf }); if (!window || window.status !== "available" || window.id !== record.id || window.lifecycle !== "active" || window.dueAt !== record.window.dueAt || !["open", "passed"].includes(window.windowState) || window.evaluatedAt !== asOf) return this.unavailable("attention-candidate-commitment-invalid"); if (!this.add(groups, record.candidateMoveId, record.candidateMoveRevision, situationId, action, { kind: "commitment", commitmentId: record.id, commitmentRevision: record.revision, lifecycle: "active", dueAt: record.window.dueAt, deadlineState: window.windowState })) return this.unavailable("attention-candidate-source-duplicate"); } }
      const routines = routineOwner.getRoutines(); if (!routines || !["available", "absent"].includes(routines.status)) return this.unavailable("attention-candidate-routine-unavailable");
      if (routines.status === "available") { if (!Array.isArray(routines.routines)) return this.unavailable("attention-candidate-routine-invalid"); const ids = new Set(); for (const record of routines.routines) { if (!record || typeof record.id !== "string" || ids.has(record.id) || !Number.isInteger(record.candidateMoveRevision) || typeof record.candidateMoveId !== "string" || !Array.isArray(record.revisions) || record.revisions.length === 0 || !["active", "paused", "retired"].includes(record.lifecycle)) return this.unavailable("attention-candidate-routine-invalid"); ids.add(record.id); if (record.lifecycle !== "active") continue; const action = this.actionFor(truth, record.candidateMoveId, record.candidateMoveRevision); const situationId = this.situationFor(truth, record.candidateMoveId); if (!action || !situationId || action !== record.action) return this.unavailable("attention-candidate-routine-invalid"); const occurrence = routineOwner.getRoutineOccurrence({ id: record.id, asOf }); if (!occurrence || occurrence.status !== "available" || !["current", "none"].includes(occurrence.occurrence)) return this.unavailable("attention-candidate-routine-invalid"); if (occurrence.occurrence === "none") continue; if (occurrence.routineId !== record.id || typeof occurrence.occurrenceKey !== "string" || !this.canonicalUtc(occurrence.opensAt) || !this.canonicalUtc(occurrence.closesAt)) return this.unavailable("attention-candidate-routine-invalid"); if (!this.add(groups, record.candidateMoveId, record.candidateMoveRevision, situationId, action, { kind: "routine-occurrence", routineId: record.id, routineRevision: record.revisions.length, occurrenceKey: occurrence.occurrenceKey, opensAt: occurrence.opensAt, closesAt: occurrence.closesAt })) return this.unavailable("attention-candidate-source-duplicate"); } }
    } catch (error) { return this.unavailable("attention-candidate-source-unavailable"); }
    const order = { move: 0, commitment: 1, "routine-occurrence": 2 }; const candidates = [...groups.values()].map((candidate) => ({ ...candidate, bases: candidate.bases.sort((left, right) => order[left.kind] - order[right.kind]) })).sort((left, right) => left.candidateMoveId.localeCompare(right.candidateMoveId) || left.candidateMoveRevision - right.candidateMoveRevision);
    return { status: "available", asOf, candidates: this.clone(candidates) };
  },
};